# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommonArtifact
#'
#' @description CommonArtifact Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field key  character [optional]
#'
#' @field path  character [optional]
#'
#' @field path_only  character [optional]
#'
#' @field artifact_type  \link{ArtifactTypeEnumArtifactType} [optional]
#'
#' @field linked_artifact_id  character [optional]
#'
#' @field filename_extension  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommonArtifact <- R6::R6Class(
  'CommonArtifact',
  public = list(
    `key` = NULL,
    `path` = NULL,
    `path_only` = NULL,
    `artifact_type` = NULL,
    `linked_artifact_id` = NULL,
    `filename_extension` = NULL,
    initialize = function(
        `key`=NULL, `path`=NULL, `path_only`=NULL, `artifact_type`=NULL, `linked_artifact_id`=NULL, `filename_extension`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!is.null(`path_only`)) {
        self$`path_only` <- `path_only`
      }
      if (!is.null(`artifact_type`)) {
        stopifnot(R6::is.R6(`artifact_type`))
        self$`artifact_type` <- `artifact_type`
      }
      if (!is.null(`linked_artifact_id`)) {
        stopifnot(is.character(`linked_artifact_id`), length(`linked_artifact_id`) == 1)
        self$`linked_artifact_id` <- `linked_artifact_id`
      }
      if (!is.null(`filename_extension`)) {
        stopifnot(is.character(`filename_extension`), length(`filename_extension`) == 1)
        self$`filename_extension` <- `filename_extension`
      }
    },
    toJSON = function() {
      CommonArtifactObject <- list()
      if (!is.null(self$`key`)) {
        CommonArtifactObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`path`)) {
        CommonArtifactObject[['path']] <-
          self$`path`
      }
      if (!is.null(self$`path_only`)) {
        CommonArtifactObject[['path_only']] <-
          self$`path_only`
      }
      if (!is.null(self$`artifact_type`)) {
        CommonArtifactObject[['artifact_type']] <-
          self$`artifact_type`$toJSON()
      }
      if (!is.null(self$`linked_artifact_id`)) {
        CommonArtifactObject[['linked_artifact_id']] <-
          self$`linked_artifact_id`
      }
      if (!is.null(self$`filename_extension`)) {
        CommonArtifactObject[['filename_extension']] <-
          self$`filename_extension`
      }

      CommonArtifactObject
    },
    fromJSON = function(CommonArtifactJson) {
      CommonArtifactObject <- jsonlite::fromJSON(CommonArtifactJson)
      if (!is.null(CommonArtifactObject$`key`)) {
        self$`key` <- CommonArtifactObject$`key`
      }
      if (!is.null(CommonArtifactObject$`path`)) {
        self$`path` <- CommonArtifactObject$`path`
      }
      if (!is.null(CommonArtifactObject$`path_only`)) {
        self$`path_only` <- CommonArtifactObject$`path_only`
      }
      if (!is.null(CommonArtifactObject$`artifact_type`)) {
        artifact_typeObject <- ArtifactTypeEnumArtifactType$new()
        artifact_typeObject$fromJSON(jsonlite::toJSON(CommonArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
        self$`artifact_type` <- artifact_typeObject
      }
      if (!is.null(CommonArtifactObject$`linked_artifact_id`)) {
        self$`linked_artifact_id` <- CommonArtifactObject$`linked_artifact_id`
      }
      if (!is.null(CommonArtifactObject$`filename_extension`)) {
        self$`filename_extension` <- CommonArtifactObject$`filename_extension`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )},
        if (!is.null(self$`path_only`)) {
        sprintf(
        '"path_only":
          "%s"
                ',
        self$`path_only`
        )},
        if (!is.null(self$`artifact_type`)) {
        sprintf(
        '"artifact_type":
        %s
        ',
        jsonlite::toJSON(self$`artifact_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`linked_artifact_id`)) {
        sprintf(
        '"linked_artifact_id":
          "%s"
                ',
        self$`linked_artifact_id`
        )},
        if (!is.null(self$`filename_extension`)) {
        sprintf(
        '"filename_extension":
          "%s"
                ',
        self$`filename_extension`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommonArtifactJson) {
      CommonArtifactObject <- jsonlite::fromJSON(CommonArtifactJson)
      self$`key` <- CommonArtifactObject$`key`
      self$`path` <- CommonArtifactObject$`path`
      self$`path_only` <- CommonArtifactObject$`path_only`
      self$`artifact_type` <- ArtifactTypeEnumArtifactType$new()$fromJSON(jsonlite::toJSON(CommonArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
      self$`linked_artifact_id` <- CommonArtifactObject$`linked_artifact_id`
      self$`filename_extension` <- CommonArtifactObject$`filename_extension`
      self
    }
  )
)

