# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommonKeyValue
#'
#' @description CommonKeyValue Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field key  character [optional]
#'
#' @field value  object [optional]
#'
#' @field value_type  \link{ValueTypeEnumValueType} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommonKeyValue <- R6::R6Class(
  'CommonKeyValue',
  public = list(
    `key` = NULL,
    `value` = NULL,
    `value_type` = NULL,
    initialize = function(
        `key`=NULL, `value`=NULL, `value_type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`value`)) {
        self$`value` <- `value`
      }
      if (!is.null(`value_type`)) {
        stopifnot(R6::is.R6(`value_type`))
        self$`value_type` <- `value_type`
      }
    },
    toJSON = function() {
      CommonKeyValueObject <- list()
      if (!is.null(self$`key`)) {
        CommonKeyValueObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`value`)) {
        CommonKeyValueObject[['value']] <-
          self$`value`
      }
      if (!is.null(self$`value_type`)) {
        CommonKeyValueObject[['value_type']] <-
          self$`value_type`$toJSON()
      }

      CommonKeyValueObject
    },
    fromJSON = function(CommonKeyValueJson) {
      CommonKeyValueObject <- jsonlite::fromJSON(CommonKeyValueJson)
      if (!is.null(CommonKeyValueObject$`key`)) {
        self$`key` <- CommonKeyValueObject$`key`
      }
      if (!is.null(CommonKeyValueObject$`value`)) {
        self$`value` <- CommonKeyValueObject$`value`
      }
      if (!is.null(CommonKeyValueObject$`value_type`)) {
        value_typeObject <- ValueTypeEnumValueType$new()
        value_typeObject$fromJSON(jsonlite::toJSON(CommonKeyValueObject$value_type, auto_unbox = TRUE, digits = NA))
        self$`value_type` <- value_typeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )},
        if (!is.null(self$`value_type`)) {
        sprintf(
        '"value_type":
        %s
        ',
        jsonlite::toJSON(self$`value_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommonKeyValueJson) {
      CommonKeyValueObject <- jsonlite::fromJSON(CommonKeyValueJson)
      self$`key` <- CommonKeyValueObject$`key`
      self$`value` <- CommonKeyValueObject$`value`
      self$`value_type` <- ValueTypeEnumValueType$new()$fromJSON(jsonlite::toJSON(CommonKeyValueObject$value_type, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

