# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommonKeyValueQuery
#'
#' @description CommonKeyValueQuery Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field key  character [optional]
#'
#' @field value  object [optional]
#'
#' @field value_type  \link{ValueTypeEnumValueType} [optional]
#'
#' @field operator  \link{OperatorEnumOperator} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommonKeyValueQuery <- R6::R6Class(
  'CommonKeyValueQuery',
  public = list(
    `key` = NULL,
    `value` = NULL,
    `value_type` = NULL,
    `operator` = NULL,
    initialize = function(
        `key`=NULL, `value`=NULL, `value_type`=NULL, `operator`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`value`)) {
        self$`value` <- `value`
      }
      if (!is.null(`value_type`)) {
        stopifnot(R6::is.R6(`value_type`))
        self$`value_type` <- `value_type`
      }
      if (!is.null(`operator`)) {
        stopifnot(R6::is.R6(`operator`))
        self$`operator` <- `operator`
      }
    },
    toJSON = function() {
      CommonKeyValueQueryObject <- list()
      if (!is.null(self$`key`)) {
        CommonKeyValueQueryObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`value`)) {
        CommonKeyValueQueryObject[['value']] <-
          self$`value`
      }
      if (!is.null(self$`value_type`)) {
        CommonKeyValueQueryObject[['value_type']] <-
          self$`value_type`$toJSON()
      }
      if (!is.null(self$`operator`)) {
        CommonKeyValueQueryObject[['operator']] <-
          self$`operator`$toJSON()
      }

      CommonKeyValueQueryObject
    },
    fromJSON = function(CommonKeyValueQueryJson) {
      CommonKeyValueQueryObject <- jsonlite::fromJSON(CommonKeyValueQueryJson)
      if (!is.null(CommonKeyValueQueryObject$`key`)) {
        self$`key` <- CommonKeyValueQueryObject$`key`
      }
      if (!is.null(CommonKeyValueQueryObject$`value`)) {
        self$`value` <- CommonKeyValueQueryObject$`value`
      }
      if (!is.null(CommonKeyValueQueryObject$`value_type`)) {
        value_typeObject <- ValueTypeEnumValueType$new()
        value_typeObject$fromJSON(jsonlite::toJSON(CommonKeyValueQueryObject$value_type, auto_unbox = TRUE, digits = NA))
        self$`value_type` <- value_typeObject
      }
      if (!is.null(CommonKeyValueQueryObject$`operator`)) {
        operatorObject <- OperatorEnumOperator$new()
        operatorObject$fromJSON(jsonlite::toJSON(CommonKeyValueQueryObject$operator, auto_unbox = TRUE, digits = NA))
        self$`operator` <- operatorObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )},
        if (!is.null(self$`value_type`)) {
        sprintf(
        '"value_type":
        %s
        ',
        jsonlite::toJSON(self$`value_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`operator`)) {
        sprintf(
        '"operator":
        %s
        ',
        jsonlite::toJSON(self$`operator`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommonKeyValueQueryJson) {
      CommonKeyValueQueryObject <- jsonlite::fromJSON(CommonKeyValueQueryJson)
      self$`key` <- CommonKeyValueQueryObject$`key`
      self$`value` <- CommonKeyValueQueryObject$`value`
      self$`value_type` <- ValueTypeEnumValueType$new()$fromJSON(jsonlite::toJSON(CommonKeyValueQueryObject$value_type, auto_unbox = TRUE, digits = NA))
      self$`operator` <- OperatorEnumOperator$new()$fromJSON(jsonlite::toJSON(CommonKeyValueQueryObject$operator, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

