# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetProjectByNameResponse
#'
#' @description ModeldbGetProjectByNameResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field project_by_user  \link{ModeldbProject} [optional]
#'
#' @field shared_projects  list( \link{ModeldbProject} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetProjectByNameResponse <- R6::R6Class(
  'ModeldbGetProjectByNameResponse',
  public = list(
    `project_by_user` = NULL,
    `shared_projects` = NULL,
    initialize = function(
        `project_by_user`=NULL, `shared_projects`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`project_by_user`)) {
        stopifnot(R6::is.R6(`project_by_user`))
        self$`project_by_user` <- `project_by_user`
      }
      if (!is.null(`shared_projects`)) {
        stopifnot(is.vector(`shared_projects`), length(`shared_projects`) != 0)
        sapply(`shared_projects`, function(x) stopifnot(R6::is.R6(x)))
        self$`shared_projects` <- `shared_projects`
      }
    },
    toJSON = function() {
      ModeldbGetProjectByNameResponseObject <- list()
      if (!is.null(self$`project_by_user`)) {
        ModeldbGetProjectByNameResponseObject[['project_by_user']] <-
          self$`project_by_user`$toJSON()
      }
      if (!is.null(self$`shared_projects`)) {
        ModeldbGetProjectByNameResponseObject[['shared_projects']] <-
          lapply(self$`shared_projects`, function(x) x$toJSON())
      }

      ModeldbGetProjectByNameResponseObject
    },
    fromJSON = function(ModeldbGetProjectByNameResponseJson) {
      ModeldbGetProjectByNameResponseObject <- jsonlite::fromJSON(ModeldbGetProjectByNameResponseJson)
      if (!is.null(ModeldbGetProjectByNameResponseObject$`project_by_user`)) {
        project_by_userObject <- ModeldbProject$new()
        project_by_userObject$fromJSON(jsonlite::toJSON(ModeldbGetProjectByNameResponseObject$project_by_user, auto_unbox = TRUE, digits = NA))
        self$`project_by_user` <- project_by_userObject
      }
      if (!is.null(ModeldbGetProjectByNameResponseObject$`shared_projects`)) {
        self$`shared_projects` <- ApiClient$new()$deserializeObj(ModeldbGetProjectByNameResponseObject$`shared_projects`, "array[ModeldbProject]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`project_by_user`)) {
        sprintf(
        '"project_by_user":
        %s
        ',
        jsonlite::toJSON(self$`project_by_user`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`shared_projects`)) {
        sprintf(
        '"shared_projects":
        [%s]
',
        paste(sapply(self$`shared_projects`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetProjectByNameResponseJson) {
      ModeldbGetProjectByNameResponseObject <- jsonlite::fromJSON(ModeldbGetProjectByNameResponseJson)
      self$`project_by_user` <- ModeldbProject$new()$fromJSON(jsonlite::toJSON(ModeldbGetProjectByNameResponseObject$project_by_user, auto_unbox = TRUE, digits = NA))
      self$`shared_projects` <- ApiClient$new()$deserializeObj(ModeldbGetProjectByNameResponseObject$`shared_projects`, "array[ModeldbProject]", loadNamespace("openapi"))
      self
    }
  )
)

