# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbFindProjects
#'
#' @description ModeldbFindProjects Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field project_ids  list( character ) [optional]
#'
#' @field predicates  list( \link{CommonKeyValueQuery} ) [optional]
#'
#' @field ids_only  character [optional]
#'
#' @field workspace_name  character [optional]
#'
#' @field page_number For pagination integer [optional]
#'
#' @field page_limit  integer [optional]
#'
#' @field ascending  character [optional]
#'
#' @field sort_key  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbFindProjects <- R6::R6Class(
  'ModeldbFindProjects',
  public = list(
    `project_ids` = NULL,
    `predicates` = NULL,
    `ids_only` = NULL,
    `workspace_name` = NULL,
    `page_number` = NULL,
    `page_limit` = NULL,
    `ascending` = NULL,
    `sort_key` = NULL,
    initialize = function(
        `project_ids`=NULL, `predicates`=NULL, `ids_only`=NULL, `workspace_name`=NULL, `page_number`=NULL, `page_limit`=NULL, `ascending`=NULL, `sort_key`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`project_ids`)) {
        stopifnot(is.vector(`project_ids`), length(`project_ids`) != 0)
        sapply(`project_ids`, function(x) stopifnot(is.character(x)))
        self$`project_ids` <- `project_ids`
      }
      if (!is.null(`predicates`)) {
        stopifnot(is.vector(`predicates`), length(`predicates`) != 0)
        sapply(`predicates`, function(x) stopifnot(R6::is.R6(x)))
        self$`predicates` <- `predicates`
      }
      if (!is.null(`ids_only`)) {
        self$`ids_only` <- `ids_only`
      }
      if (!is.null(`workspace_name`)) {
        stopifnot(is.character(`workspace_name`), length(`workspace_name`) == 1)
        self$`workspace_name` <- `workspace_name`
      }
      if (!is.null(`page_number`)) {
        stopifnot(is.numeric(`page_number`), length(`page_number`) == 1)
        self$`page_number` <- `page_number`
      }
      if (!is.null(`page_limit`)) {
        stopifnot(is.numeric(`page_limit`), length(`page_limit`) == 1)
        self$`page_limit` <- `page_limit`
      }
      if (!is.null(`ascending`)) {
        self$`ascending` <- `ascending`
      }
      if (!is.null(`sort_key`)) {
        stopifnot(is.character(`sort_key`), length(`sort_key`) == 1)
        self$`sort_key` <- `sort_key`
      }
    },
    toJSON = function() {
      ModeldbFindProjectsObject <- list()
      if (!is.null(self$`project_ids`)) {
        ModeldbFindProjectsObject[['project_ids']] <-
          self$`project_ids`
      }
      if (!is.null(self$`predicates`)) {
        ModeldbFindProjectsObject[['predicates']] <-
          lapply(self$`predicates`, function(x) x$toJSON())
      }
      if (!is.null(self$`ids_only`)) {
        ModeldbFindProjectsObject[['ids_only']] <-
          self$`ids_only`
      }
      if (!is.null(self$`workspace_name`)) {
        ModeldbFindProjectsObject[['workspace_name']] <-
          self$`workspace_name`
      }
      if (!is.null(self$`page_number`)) {
        ModeldbFindProjectsObject[['page_number']] <-
          self$`page_number`
      }
      if (!is.null(self$`page_limit`)) {
        ModeldbFindProjectsObject[['page_limit']] <-
          self$`page_limit`
      }
      if (!is.null(self$`ascending`)) {
        ModeldbFindProjectsObject[['ascending']] <-
          self$`ascending`
      }
      if (!is.null(self$`sort_key`)) {
        ModeldbFindProjectsObject[['sort_key']] <-
          self$`sort_key`
      }

      ModeldbFindProjectsObject
    },
    fromJSON = function(ModeldbFindProjectsJson) {
      ModeldbFindProjectsObject <- jsonlite::fromJSON(ModeldbFindProjectsJson)
      if (!is.null(ModeldbFindProjectsObject$`project_ids`)) {
        self$`project_ids` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsObject$`project_ids`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbFindProjectsObject$`predicates`)) {
        self$`predicates` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbFindProjectsObject$`ids_only`)) {
        self$`ids_only` <- ModeldbFindProjectsObject$`ids_only`
      }
      if (!is.null(ModeldbFindProjectsObject$`workspace_name`)) {
        self$`workspace_name` <- ModeldbFindProjectsObject$`workspace_name`
      }
      if (!is.null(ModeldbFindProjectsObject$`page_number`)) {
        self$`page_number` <- ModeldbFindProjectsObject$`page_number`
      }
      if (!is.null(ModeldbFindProjectsObject$`page_limit`)) {
        self$`page_limit` <- ModeldbFindProjectsObject$`page_limit`
      }
      if (!is.null(ModeldbFindProjectsObject$`ascending`)) {
        self$`ascending` <- ModeldbFindProjectsObject$`ascending`
      }
      if (!is.null(ModeldbFindProjectsObject$`sort_key`)) {
        self$`sort_key` <- ModeldbFindProjectsObject$`sort_key`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`project_ids`)) {
        sprintf(
        '"project_ids":
           [%s]
        ',
        paste(unlist(lapply(self$`project_ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`predicates`)) {
        sprintf(
        '"predicates":
        [%s]
',
        paste(sapply(self$`predicates`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`ids_only`)) {
        sprintf(
        '"ids_only":
          "%s"
                ',
        self$`ids_only`
        )},
        if (!is.null(self$`workspace_name`)) {
        sprintf(
        '"workspace_name":
          "%s"
                ',
        self$`workspace_name`
        )},
        if (!is.null(self$`page_number`)) {
        sprintf(
        '"page_number":
          %d
                ',
        self$`page_number`
        )},
        if (!is.null(self$`page_limit`)) {
        sprintf(
        '"page_limit":
          %d
                ',
        self$`page_limit`
        )},
        if (!is.null(self$`ascending`)) {
        sprintf(
        '"ascending":
          "%s"
                ',
        self$`ascending`
        )},
        if (!is.null(self$`sort_key`)) {
        sprintf(
        '"sort_key":
          "%s"
                ',
        self$`sort_key`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbFindProjectsJson) {
      ModeldbFindProjectsObject <- jsonlite::fromJSON(ModeldbFindProjectsJson)
      self$`project_ids` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsObject$`project_ids`, "array[character]", loadNamespace("openapi"))
      self$`predicates` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      self$`ids_only` <- ModeldbFindProjectsObject$`ids_only`
      self$`workspace_name` <- ModeldbFindProjectsObject$`workspace_name`
      self$`page_number` <- ModeldbFindProjectsObject$`page_number`
      self$`page_limit` <- ModeldbFindProjectsObject$`page_limit`
      self$`ascending` <- ModeldbFindProjectsObject$`ascending`
      self$`sort_key` <- ModeldbFindProjectsObject$`sort_key`
      self
    }
  )
)

