# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbSetProjectReadme
#'
#' @description ModeldbSetProjectReadme Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field readme_text  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbSetProjectReadme <- R6::R6Class(
  'ModeldbSetProjectReadme',
  public = list(
    `id` = NULL,
    `readme_text` = NULL,
    initialize = function(
        `id`=NULL, `readme_text`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
    },
    toJSON = function() {
      ModeldbSetProjectReadmeObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbSetProjectReadmeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`readme_text`)) {
        ModeldbSetProjectReadmeObject[['readme_text']] <-
          self$`readme_text`
      }

      ModeldbSetProjectReadmeObject
    },
    fromJSON = function(ModeldbSetProjectReadmeJson) {
      ModeldbSetProjectReadmeObject <- jsonlite::fromJSON(ModeldbSetProjectReadmeJson)
      if (!is.null(ModeldbSetProjectReadmeObject$`id`)) {
        self$`id` <- ModeldbSetProjectReadmeObject$`id`
      }
      if (!is.null(ModeldbSetProjectReadmeObject$`readme_text`)) {
        self$`readme_text` <- ModeldbSetProjectReadmeObject$`readme_text`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbSetProjectReadmeJson) {
      ModeldbSetProjectReadmeObject <- jsonlite::fromJSON(ModeldbSetProjectReadmeJson)
      self$`id` <- ModeldbSetProjectReadmeObject$`id`
      self$`readme_text` <- ModeldbSetProjectReadmeObject$`readme_text`
      self
    }
  )
)

