# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbFindProjectsResponse
#'
#' @description ModeldbFindProjectsResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field projects  list( \link{ModeldbProject} ) [optional]
#'
#' @field total_records  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbFindProjectsResponse <- R6::R6Class(
  'ModeldbFindProjectsResponse',
  public = list(
    `projects` = NULL,
    `total_records` = NULL,
    initialize = function(
        `projects`=NULL, `total_records`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`projects`)) {
        stopifnot(is.vector(`projects`), length(`projects`) != 0)
        sapply(`projects`, function(x) stopifnot(R6::is.R6(x)))
        self$`projects` <- `projects`
      }
      if (!is.null(`total_records`)) {
        stopifnot(is.character(`total_records`), length(`total_records`) == 1)
        self$`total_records` <- `total_records`
      }
    },
    toJSON = function() {
      ModeldbFindProjectsResponseObject <- list()
      if (!is.null(self$`projects`)) {
        ModeldbFindProjectsResponseObject[['projects']] <-
          lapply(self$`projects`, function(x) x$toJSON())
      }
      if (!is.null(self$`total_records`)) {
        ModeldbFindProjectsResponseObject[['total_records']] <-
          self$`total_records`
      }

      ModeldbFindProjectsResponseObject
    },
    fromJSON = function(ModeldbFindProjectsResponseJson) {
      ModeldbFindProjectsResponseObject <- jsonlite::fromJSON(ModeldbFindProjectsResponseJson)
      if (!is.null(ModeldbFindProjectsResponseObject$`projects`)) {
        self$`projects` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsResponseObject$`projects`, "array[ModeldbProject]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbFindProjectsResponseObject$`total_records`)) {
        self$`total_records` <- ModeldbFindProjectsResponseObject$`total_records`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`projects`)) {
        sprintf(
        '"projects":
        [%s]
',
        paste(sapply(self$`projects`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`total_records`)) {
        sprintf(
        '"total_records":
          "%s"
                ',
        self$`total_records`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbFindProjectsResponseJson) {
      ModeldbFindProjectsResponseObject <- jsonlite::fromJSON(ModeldbFindProjectsResponseJson)
      self$`projects` <- ApiClient$new()$deserializeObj(ModeldbFindProjectsResponseObject$`projects`, "array[ModeldbProject]", loadNamespace("openapi"))
      self$`total_records` <- ModeldbFindProjectsResponseObject$`total_records`
      self
    }
  )
)

