# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetProjectCodeVersionResponse
#'
#' @description ModeldbGetProjectCodeVersionResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code_version  \link{ModeldbCodeVersion} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetProjectCodeVersionResponse <- R6::R6Class(
  'ModeldbGetProjectCodeVersionResponse',
  public = list(
    `code_version` = NULL,
    initialize = function(
        `code_version`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`code_version`)) {
        stopifnot(R6::is.R6(`code_version`))
        self$`code_version` <- `code_version`
      }
    },
    toJSON = function() {
      ModeldbGetProjectCodeVersionResponseObject <- list()
      if (!is.null(self$`code_version`)) {
        ModeldbGetProjectCodeVersionResponseObject[['code_version']] <-
          self$`code_version`$toJSON()
      }

      ModeldbGetProjectCodeVersionResponseObject
    },
    fromJSON = function(ModeldbGetProjectCodeVersionResponseJson) {
      ModeldbGetProjectCodeVersionResponseObject <- jsonlite::fromJSON(ModeldbGetProjectCodeVersionResponseJson)
      if (!is.null(ModeldbGetProjectCodeVersionResponseObject$`code_version`)) {
        code_versionObject <- ModeldbCodeVersion$new()
        code_versionObject$fromJSON(jsonlite::toJSON(ModeldbGetProjectCodeVersionResponseObject$code_version, auto_unbox = TRUE, digits = NA))
        self$`code_version` <- code_versionObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code_version`)) {
        sprintf(
        '"code_version":
        %s
        ',
        jsonlite::toJSON(self$`code_version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetProjectCodeVersionResponseJson) {
      ModeldbGetProjectCodeVersionResponseObject <- jsonlite::fromJSON(ModeldbGetProjectCodeVersionResponseJson)
      self$`code_version` <- ModeldbCodeVersion$new()$fromJSON(jsonlite::toJSON(ModeldbGetProjectCodeVersionResponseObject$code_version, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

