# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbCodeVersion
#'
#' @description ModeldbCodeVersion Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field git_snapshot  \link{ModeldbGitSnapshot} [optional]
#'
#' @field code_archive  \link{CommonArtifact} [optional]
#'
#' @field date_logged  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbCodeVersion <- R6::R6Class(
  'ModeldbCodeVersion',
  public = list(
    `git_snapshot` = NULL,
    `code_archive` = NULL,
    `date_logged` = NULL,
    initialize = function(
        `git_snapshot`=NULL, `code_archive`=NULL, `date_logged`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`git_snapshot`)) {
        stopifnot(R6::is.R6(`git_snapshot`))
        self$`git_snapshot` <- `git_snapshot`
      }
      if (!is.null(`code_archive`)) {
        stopifnot(R6::is.R6(`code_archive`))
        self$`code_archive` <- `code_archive`
      }
      if (!is.null(`date_logged`)) {
        stopifnot(is.character(`date_logged`), length(`date_logged`) == 1)
        self$`date_logged` <- `date_logged`
      }
    },
    toJSON = function() {
      ModeldbCodeVersionObject <- list()
      if (!is.null(self$`git_snapshot`)) {
        ModeldbCodeVersionObject[['git_snapshot']] <-
          self$`git_snapshot`$toJSON()
      }
      if (!is.null(self$`code_archive`)) {
        ModeldbCodeVersionObject[['code_archive']] <-
          self$`code_archive`$toJSON()
      }
      if (!is.null(self$`date_logged`)) {
        ModeldbCodeVersionObject[['date_logged']] <-
          self$`date_logged`
      }

      ModeldbCodeVersionObject
    },
    fromJSON = function(ModeldbCodeVersionJson) {
      ModeldbCodeVersionObject <- jsonlite::fromJSON(ModeldbCodeVersionJson)
      if (!is.null(ModeldbCodeVersionObject$`git_snapshot`)) {
        git_snapshotObject <- ModeldbGitSnapshot$new()
        git_snapshotObject$fromJSON(jsonlite::toJSON(ModeldbCodeVersionObject$git_snapshot, auto_unbox = TRUE, digits = NA))
        self$`git_snapshot` <- git_snapshotObject
      }
      if (!is.null(ModeldbCodeVersionObject$`code_archive`)) {
        code_archiveObject <- CommonArtifact$new()
        code_archiveObject$fromJSON(jsonlite::toJSON(ModeldbCodeVersionObject$code_archive, auto_unbox = TRUE, digits = NA))
        self$`code_archive` <- code_archiveObject
      }
      if (!is.null(ModeldbCodeVersionObject$`date_logged`)) {
        self$`date_logged` <- ModeldbCodeVersionObject$`date_logged`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`git_snapshot`)) {
        sprintf(
        '"git_snapshot":
        %s
        ',
        jsonlite::toJSON(self$`git_snapshot`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`code_archive`)) {
        sprintf(
        '"code_archive":
        %s
        ',
        jsonlite::toJSON(self$`code_archive`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`date_logged`)) {
        sprintf(
        '"date_logged":
          "%s"
                ',
        self$`date_logged`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbCodeVersionJson) {
      ModeldbCodeVersionObject <- jsonlite::fromJSON(ModeldbCodeVersionJson)
      self$`git_snapshot` <- ModeldbGitSnapshot$new()$fromJSON(jsonlite::toJSON(ModeldbCodeVersionObject$git_snapshot, auto_unbox = TRUE, digits = NA))
      self$`code_archive` <- CommonArtifact$new()$fromJSON(jsonlite::toJSON(ModeldbCodeVersionObject$code_archive, auto_unbox = TRUE, digits = NA))
      self$`date_logged` <- ModeldbCodeVersionObject$`date_logged`
      self
    }
  )
)

