# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetSummaryResponse
#'
#' @description ModeldbGetSummaryResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field last_updated_time  character [optional]
#'
#' @field total_experiment  character [optional]
#'
#' @field total_experiment_runs  character [optional]
#'
#' @field last_modified_experimentRun_summary  \link{ModeldbLastModifiedExperimentRunSummary} [optional]
#'
#' @field metrics  list( \link{ModeldbMetricsSummary} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetSummaryResponse <- R6::R6Class(
  'ModeldbGetSummaryResponse',
  public = list(
    `name` = NULL,
    `last_updated_time` = NULL,
    `total_experiment` = NULL,
    `total_experiment_runs` = NULL,
    `last_modified_experimentRun_summary` = NULL,
    `metrics` = NULL,
    initialize = function(
        `name`=NULL, `last_updated_time`=NULL, `total_experiment`=NULL, `total_experiment_runs`=NULL, `last_modified_experimentRun_summary`=NULL, `metrics`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`last_updated_time`)) {
        stopifnot(is.character(`last_updated_time`), length(`last_updated_time`) == 1)
        self$`last_updated_time` <- `last_updated_time`
      }
      if (!is.null(`total_experiment`)) {
        stopifnot(is.character(`total_experiment`), length(`total_experiment`) == 1)
        self$`total_experiment` <- `total_experiment`
      }
      if (!is.null(`total_experiment_runs`)) {
        stopifnot(is.character(`total_experiment_runs`), length(`total_experiment_runs`) == 1)
        self$`total_experiment_runs` <- `total_experiment_runs`
      }
      if (!is.null(`last_modified_experimentRun_summary`)) {
        stopifnot(R6::is.R6(`last_modified_experimentRun_summary`))
        self$`last_modified_experimentRun_summary` <- `last_modified_experimentRun_summary`
      }
      if (!is.null(`metrics`)) {
        stopifnot(is.vector(`metrics`), length(`metrics`) != 0)
        sapply(`metrics`, function(x) stopifnot(R6::is.R6(x)))
        self$`metrics` <- `metrics`
      }
    },
    toJSON = function() {
      ModeldbGetSummaryResponseObject <- list()
      if (!is.null(self$`name`)) {
        ModeldbGetSummaryResponseObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`last_updated_time`)) {
        ModeldbGetSummaryResponseObject[['last_updated_time']] <-
          self$`last_updated_time`
      }
      if (!is.null(self$`total_experiment`)) {
        ModeldbGetSummaryResponseObject[['total_experiment']] <-
          self$`total_experiment`
      }
      if (!is.null(self$`total_experiment_runs`)) {
        ModeldbGetSummaryResponseObject[['total_experiment_runs']] <-
          self$`total_experiment_runs`
      }
      if (!is.null(self$`last_modified_experimentRun_summary`)) {
        ModeldbGetSummaryResponseObject[['last_modified_experimentRun_summary']] <-
          self$`last_modified_experimentRun_summary`$toJSON()
      }
      if (!is.null(self$`metrics`)) {
        ModeldbGetSummaryResponseObject[['metrics']] <-
          lapply(self$`metrics`, function(x) x$toJSON())
      }

      ModeldbGetSummaryResponseObject
    },
    fromJSON = function(ModeldbGetSummaryResponseJson) {
      ModeldbGetSummaryResponseObject <- jsonlite::fromJSON(ModeldbGetSummaryResponseJson)
      if (!is.null(ModeldbGetSummaryResponseObject$`name`)) {
        self$`name` <- ModeldbGetSummaryResponseObject$`name`
      }
      if (!is.null(ModeldbGetSummaryResponseObject$`last_updated_time`)) {
        self$`last_updated_time` <- ModeldbGetSummaryResponseObject$`last_updated_time`
      }
      if (!is.null(ModeldbGetSummaryResponseObject$`total_experiment`)) {
        self$`total_experiment` <- ModeldbGetSummaryResponseObject$`total_experiment`
      }
      if (!is.null(ModeldbGetSummaryResponseObject$`total_experiment_runs`)) {
        self$`total_experiment_runs` <- ModeldbGetSummaryResponseObject$`total_experiment_runs`
      }
      if (!is.null(ModeldbGetSummaryResponseObject$`last_modified_experimentRun_summary`)) {
        last_modified_experimentRun_summaryObject <- ModeldbLastModifiedExperimentRunSummary$new()
        last_modified_experimentRun_summaryObject$fromJSON(jsonlite::toJSON(ModeldbGetSummaryResponseObject$last_modified_experimentRun_summary, auto_unbox = TRUE, digits = NA))
        self$`last_modified_experimentRun_summary` <- last_modified_experimentRun_summaryObject
      }
      if (!is.null(ModeldbGetSummaryResponseObject$`metrics`)) {
        self$`metrics` <- ApiClient$new()$deserializeObj(ModeldbGetSummaryResponseObject$`metrics`, "array[ModeldbMetricsSummary]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`last_updated_time`)) {
        sprintf(
        '"last_updated_time":
          "%s"
                ',
        self$`last_updated_time`
        )},
        if (!is.null(self$`total_experiment`)) {
        sprintf(
        '"total_experiment":
          "%s"
                ',
        self$`total_experiment`
        )},
        if (!is.null(self$`total_experiment_runs`)) {
        sprintf(
        '"total_experiment_runs":
          "%s"
                ',
        self$`total_experiment_runs`
        )},
        if (!is.null(self$`last_modified_experimentRun_summary`)) {
        sprintf(
        '"last_modified_experimentRun_summary":
        %s
        ',
        jsonlite::toJSON(self$`last_modified_experimentRun_summary`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`metrics`)) {
        sprintf(
        '"metrics":
        [%s]
',
        paste(sapply(self$`metrics`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetSummaryResponseJson) {
      ModeldbGetSummaryResponseObject <- jsonlite::fromJSON(ModeldbGetSummaryResponseJson)
      self$`name` <- ModeldbGetSummaryResponseObject$`name`
      self$`last_updated_time` <- ModeldbGetSummaryResponseObject$`last_updated_time`
      self$`total_experiment` <- ModeldbGetSummaryResponseObject$`total_experiment`
      self$`total_experiment_runs` <- ModeldbGetSummaryResponseObject$`total_experiment_runs`
      self$`last_modified_experimentRun_summary` <- ModeldbLastModifiedExperimentRunSummary$new()$fromJSON(jsonlite::toJSON(ModeldbGetSummaryResponseObject$last_modified_experimentRun_summary, auto_unbox = TRUE, digits = NA))
      self$`metrics` <- ApiClient$new()$deserializeObj(ModeldbGetSummaryResponseObject$`metrics`, "array[ModeldbMetricsSummary]", loadNamespace("openapi"))
      self
    }
  )
)

