# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeleteProjectTags
#'
#' @description ModeldbDeleteProjectTags Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @field delete_all  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeleteProjectTags <- R6::R6Class(
  'ModeldbDeleteProjectTags',
  public = list(
    `id` = NULL,
    `tags` = NULL,
    `delete_all` = NULL,
    initialize = function(
        `id`=NULL, `tags`=NULL, `delete_all`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!is.null(`delete_all`)) {
        self$`delete_all` <- `delete_all`
      }
    },
    toJSON = function() {
      ModeldbDeleteProjectTagsObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbDeleteProjectTagsObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`tags`)) {
        ModeldbDeleteProjectTagsObject[['tags']] <-
          self$`tags`
      }
      if (!is.null(self$`delete_all`)) {
        ModeldbDeleteProjectTagsObject[['delete_all']] <-
          self$`delete_all`
      }

      ModeldbDeleteProjectTagsObject
    },
    fromJSON = function(ModeldbDeleteProjectTagsJson) {
      ModeldbDeleteProjectTagsObject <- jsonlite::fromJSON(ModeldbDeleteProjectTagsJson)
      if (!is.null(ModeldbDeleteProjectTagsObject$`id`)) {
        self$`id` <- ModeldbDeleteProjectTagsObject$`id`
      }
      if (!is.null(ModeldbDeleteProjectTagsObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectTagsObject$`tags`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbDeleteProjectTagsObject$`delete_all`)) {
        self$`delete_all` <- ModeldbDeleteProjectTagsObject$`delete_all`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`delete_all`)) {
        sprintf(
        '"delete_all":
          "%s"
                ',
        self$`delete_all`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeleteProjectTagsJson) {
      ModeldbDeleteProjectTagsObject <- jsonlite::fromJSON(ModeldbDeleteProjectTagsJson)
      self$`id` <- ModeldbDeleteProjectTagsObject$`id`
      self$`tags` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectTagsObject$`tags`, "array[character]", loadNamespace("openapi"))
      self$`delete_all` <- ModeldbDeleteProjectTagsObject$`delete_all`
      self
    }
  )
)

