# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbAddProjectAttributes
#'
#' @description ModeldbAddProjectAttributes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field attributes  list( \link{CommonKeyValue} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbAddProjectAttributes <- R6::R6Class(
  'ModeldbAddProjectAttributes',
  public = list(
    `id` = NULL,
    `attributes` = NULL,
    initialize = function(
        `id`=NULL, `attributes`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
    },
    toJSON = function() {
      ModeldbAddProjectAttributesObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbAddProjectAttributesObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`attributes`)) {
        ModeldbAddProjectAttributesObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }

      ModeldbAddProjectAttributesObject
    },
    fromJSON = function(ModeldbAddProjectAttributesJson) {
      ModeldbAddProjectAttributesObject <- jsonlite::fromJSON(ModeldbAddProjectAttributesJson)
      if (!is.null(ModeldbAddProjectAttributesObject$`id`)) {
        self$`id` <- ModeldbAddProjectAttributesObject$`id`
      }
      if (!is.null(ModeldbAddProjectAttributesObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbAddProjectAttributesObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbAddProjectAttributesJson) {
      ModeldbAddProjectAttributesObject <- jsonlite::fromJSON(ModeldbAddProjectAttributesJson)
      self$`id` <- ModeldbAddProjectAttributesObject$`id`
      self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbAddProjectAttributesObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self
    }
  )
)

