# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetUrlForArtifact
#'
#' @description ModeldbGetUrlForArtifact Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field key  character [optional]
#'
#' @field method  character [optional]
#'
#' @field artifact_type  \link{ArtifactTypeEnumArtifactType} [optional]
#'
#' @field part_number  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetUrlForArtifact <- R6::R6Class(
  'ModeldbGetUrlForArtifact',
  public = list(
    `id` = NULL,
    `key` = NULL,
    `method` = NULL,
    `artifact_type` = NULL,
    `part_number` = NULL,
    initialize = function(
        `id`=NULL, `key`=NULL, `method`=NULL, `artifact_type`=NULL, `part_number`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`method`)) {
        stopifnot(is.character(`method`), length(`method`) == 1)
        self$`method` <- `method`
      }
      if (!is.null(`artifact_type`)) {
        stopifnot(R6::is.R6(`artifact_type`))
        self$`artifact_type` <- `artifact_type`
      }
      if (!is.null(`part_number`)) {
        stopifnot(is.character(`part_number`), length(`part_number`) == 1)
        self$`part_number` <- `part_number`
      }
    },
    toJSON = function() {
      ModeldbGetUrlForArtifactObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbGetUrlForArtifactObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`key`)) {
        ModeldbGetUrlForArtifactObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`method`)) {
        ModeldbGetUrlForArtifactObject[['method']] <-
          self$`method`
      }
      if (!is.null(self$`artifact_type`)) {
        ModeldbGetUrlForArtifactObject[['artifact_type']] <-
          self$`artifact_type`$toJSON()
      }
      if (!is.null(self$`part_number`)) {
        ModeldbGetUrlForArtifactObject[['part_number']] <-
          self$`part_number`
      }

      ModeldbGetUrlForArtifactObject
    },
    fromJSON = function(ModeldbGetUrlForArtifactJson) {
      ModeldbGetUrlForArtifactObject <- jsonlite::fromJSON(ModeldbGetUrlForArtifactJson)
      if (!is.null(ModeldbGetUrlForArtifactObject$`id`)) {
        self$`id` <- ModeldbGetUrlForArtifactObject$`id`
      }
      if (!is.null(ModeldbGetUrlForArtifactObject$`key`)) {
        self$`key` <- ModeldbGetUrlForArtifactObject$`key`
      }
      if (!is.null(ModeldbGetUrlForArtifactObject$`method`)) {
        self$`method` <- ModeldbGetUrlForArtifactObject$`method`
      }
      if (!is.null(ModeldbGetUrlForArtifactObject$`artifact_type`)) {
        artifact_typeObject <- ArtifactTypeEnumArtifactType$new()
        artifact_typeObject$fromJSON(jsonlite::toJSON(ModeldbGetUrlForArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
        self$`artifact_type` <- artifact_typeObject
      }
      if (!is.null(ModeldbGetUrlForArtifactObject$`part_number`)) {
        self$`part_number` <- ModeldbGetUrlForArtifactObject$`part_number`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`method`)) {
        sprintf(
        '"method":
          "%s"
                ',
        self$`method`
        )},
        if (!is.null(self$`artifact_type`)) {
        sprintf(
        '"artifact_type":
        %s
        ',
        jsonlite::toJSON(self$`artifact_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`part_number`)) {
        sprintf(
        '"part_number":
          "%s"
                ',
        self$`part_number`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetUrlForArtifactJson) {
      ModeldbGetUrlForArtifactObject <- jsonlite::fromJSON(ModeldbGetUrlForArtifactJson)
      self$`id` <- ModeldbGetUrlForArtifactObject$`id`
      self$`key` <- ModeldbGetUrlForArtifactObject$`key`
      self$`method` <- ModeldbGetUrlForArtifactObject$`method`
      self$`artifact_type` <- ArtifactTypeEnumArtifactType$new()$fromJSON(jsonlite::toJSON(ModeldbGetUrlForArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
      self$`part_number` <- ModeldbGetUrlForArtifactObject$`part_number`
      self
    }
  )
)

