# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbProject
#'
#' @description ModeldbProject Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @field date_created  character [optional]
#'
#' @field date_updated  character [optional]
#'
#' @field short_name  character [optional]
#'
#' @field readme_text  character [optional]
#'
#' @field project_visibility  \link{ModeldbProjectVisibility} [optional]
#'
#' @field workspace_id  character [optional]
#'
#' @field workspace_type  \link{WorkspaceTypeEnumWorkspaceType} [optional]
#'
#' @field workspace_service_id  character [optional]
#'
#' @field custom_permission  \link{UacCollaboratorPermissions} [optional]
#'
#' @field visibility  \link{UacResourceVisibility} [optional]
#'
#' @field attributes  list( \link{CommonKeyValue} ) [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @field owner  character [optional]
#'
#' @field code_version_snapshot  \link{ModeldbCodeVersion} [optional]
#'
#' @field artifacts  list( \link{CommonArtifact} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbProject <- R6::R6Class(
  'ModeldbProject',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `description` = NULL,
    `date_created` = NULL,
    `date_updated` = NULL,
    `short_name` = NULL,
    `readme_text` = NULL,
    `project_visibility` = NULL,
    `workspace_id` = NULL,
    `workspace_type` = NULL,
    `workspace_service_id` = NULL,
    `custom_permission` = NULL,
    `visibility` = NULL,
    `attributes` = NULL,
    `tags` = NULL,
    `owner` = NULL,
    `code_version_snapshot` = NULL,
    `artifacts` = NULL,
    initialize = function(
        `id`=NULL, `name`=NULL, `description`=NULL, `date_created`=NULL, `date_updated`=NULL, `short_name`=NULL, `readme_text`=NULL, `project_visibility`=NULL, `workspace_id`=NULL, `workspace_type`=NULL, `workspace_service_id`=NULL, `custom_permission`=NULL, `visibility`=NULL, `attributes`=NULL, `tags`=NULL, `owner`=NULL, `code_version_snapshot`=NULL, `artifacts`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`date_created`)) {
        stopifnot(is.character(`date_created`), length(`date_created`) == 1)
        self$`date_created` <- `date_created`
      }
      if (!is.null(`date_updated`)) {
        stopifnot(is.character(`date_updated`), length(`date_updated`) == 1)
        self$`date_updated` <- `date_updated`
      }
      if (!is.null(`short_name`)) {
        stopifnot(is.character(`short_name`), length(`short_name`) == 1)
        self$`short_name` <- `short_name`
      }
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
      if (!is.null(`project_visibility`)) {
        stopifnot(R6::is.R6(`project_visibility`))
        self$`project_visibility` <- `project_visibility`
      }
      if (!is.null(`workspace_id`)) {
        stopifnot(is.character(`workspace_id`), length(`workspace_id`) == 1)
        self$`workspace_id` <- `workspace_id`
      }
      if (!is.null(`workspace_type`)) {
        stopifnot(R6::is.R6(`workspace_type`))
        self$`workspace_type` <- `workspace_type`
      }
      if (!is.null(`workspace_service_id`)) {
        stopifnot(is.character(`workspace_service_id`), length(`workspace_service_id`) == 1)
        self$`workspace_service_id` <- `workspace_service_id`
      }
      if (!is.null(`custom_permission`)) {
        stopifnot(R6::is.R6(`custom_permission`))
        self$`custom_permission` <- `custom_permission`
      }
      if (!is.null(`visibility`)) {
        stopifnot(R6::is.R6(`visibility`))
        self$`visibility` <- `visibility`
      }
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!is.null(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!is.null(`code_version_snapshot`)) {
        stopifnot(R6::is.R6(`code_version_snapshot`))
        self$`code_version_snapshot` <- `code_version_snapshot`
      }
      if (!is.null(`artifacts`)) {
        stopifnot(is.vector(`artifacts`), length(`artifacts`) != 0)
        sapply(`artifacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artifacts` <- `artifacts`
      }
    },
    toJSON = function() {
      ModeldbProjectObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbProjectObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ModeldbProjectObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        ModeldbProjectObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`date_created`)) {
        ModeldbProjectObject[['date_created']] <-
          self$`date_created`
      }
      if (!is.null(self$`date_updated`)) {
        ModeldbProjectObject[['date_updated']] <-
          self$`date_updated`
      }
      if (!is.null(self$`short_name`)) {
        ModeldbProjectObject[['short_name']] <-
          self$`short_name`
      }
      if (!is.null(self$`readme_text`)) {
        ModeldbProjectObject[['readme_text']] <-
          self$`readme_text`
      }
      if (!is.null(self$`project_visibility`)) {
        ModeldbProjectObject[['project_visibility']] <-
          self$`project_visibility`$toJSON()
      }
      if (!is.null(self$`workspace_id`)) {
        ModeldbProjectObject[['workspace_id']] <-
          self$`workspace_id`
      }
      if (!is.null(self$`workspace_type`)) {
        ModeldbProjectObject[['workspace_type']] <-
          self$`workspace_type`$toJSON()
      }
      if (!is.null(self$`workspace_service_id`)) {
        ModeldbProjectObject[['workspace_service_id']] <-
          self$`workspace_service_id`
      }
      if (!is.null(self$`custom_permission`)) {
        ModeldbProjectObject[['custom_permission']] <-
          self$`custom_permission`$toJSON()
      }
      if (!is.null(self$`visibility`)) {
        ModeldbProjectObject[['visibility']] <-
          self$`visibility`$toJSON()
      }
      if (!is.null(self$`attributes`)) {
        ModeldbProjectObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`tags`)) {
        ModeldbProjectObject[['tags']] <-
          self$`tags`
      }
      if (!is.null(self$`owner`)) {
        ModeldbProjectObject[['owner']] <-
          self$`owner`
      }
      if (!is.null(self$`code_version_snapshot`)) {
        ModeldbProjectObject[['code_version_snapshot']] <-
          self$`code_version_snapshot`$toJSON()
      }
      if (!is.null(self$`artifacts`)) {
        ModeldbProjectObject[['artifacts']] <-
          lapply(self$`artifacts`, function(x) x$toJSON())
      }

      ModeldbProjectObject
    },
    fromJSON = function(ModeldbProjectJson) {
      ModeldbProjectObject <- jsonlite::fromJSON(ModeldbProjectJson)
      if (!is.null(ModeldbProjectObject$`id`)) {
        self$`id` <- ModeldbProjectObject$`id`
      }
      if (!is.null(ModeldbProjectObject$`name`)) {
        self$`name` <- ModeldbProjectObject$`name`
      }
      if (!is.null(ModeldbProjectObject$`description`)) {
        self$`description` <- ModeldbProjectObject$`description`
      }
      if (!is.null(ModeldbProjectObject$`date_created`)) {
        self$`date_created` <- ModeldbProjectObject$`date_created`
      }
      if (!is.null(ModeldbProjectObject$`date_updated`)) {
        self$`date_updated` <- ModeldbProjectObject$`date_updated`
      }
      if (!is.null(ModeldbProjectObject$`short_name`)) {
        self$`short_name` <- ModeldbProjectObject$`short_name`
      }
      if (!is.null(ModeldbProjectObject$`readme_text`)) {
        self$`readme_text` <- ModeldbProjectObject$`readme_text`
      }
      if (!is.null(ModeldbProjectObject$`project_visibility`)) {
        project_visibilityObject <- ModeldbProjectVisibility$new()
        project_visibilityObject$fromJSON(jsonlite::toJSON(ModeldbProjectObject$project_visibility, auto_unbox = TRUE, digits = NA))
        self$`project_visibility` <- project_visibilityObject
      }
      if (!is.null(ModeldbProjectObject$`workspace_id`)) {
        self$`workspace_id` <- ModeldbProjectObject$`workspace_id`
      }
      if (!is.null(ModeldbProjectObject$`workspace_type`)) {
        workspace_typeObject <- WorkspaceTypeEnumWorkspaceType$new()
        workspace_typeObject$fromJSON(jsonlite::toJSON(ModeldbProjectObject$workspace_type, auto_unbox = TRUE, digits = NA))
        self$`workspace_type` <- workspace_typeObject
      }
      if (!is.null(ModeldbProjectObject$`workspace_service_id`)) {
        self$`workspace_service_id` <- ModeldbProjectObject$`workspace_service_id`
      }
      if (!is.null(ModeldbProjectObject$`custom_permission`)) {
        custom_permissionObject <- UacCollaboratorPermissions$new()
        custom_permissionObject$fromJSON(jsonlite::toJSON(ModeldbProjectObject$custom_permission, auto_unbox = TRUE, digits = NA))
        self$`custom_permission` <- custom_permissionObject
      }
      if (!is.null(ModeldbProjectObject$`visibility`)) {
        visibilityObject <- UacResourceVisibility$new()
        visibilityObject$fromJSON(jsonlite::toJSON(ModeldbProjectObject$visibility, auto_unbox = TRUE, digits = NA))
        self$`visibility` <- visibilityObject
      }
      if (!is.null(ModeldbProjectObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbProjectObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`tags`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbProjectObject$`owner`)) {
        self$`owner` <- ModeldbProjectObject$`owner`
      }
      if (!is.null(ModeldbProjectObject$`code_version_snapshot`)) {
        code_version_snapshotObject <- ModeldbCodeVersion$new()
        code_version_snapshotObject$fromJSON(jsonlite::toJSON(ModeldbProjectObject$code_version_snapshot, auto_unbox = TRUE, digits = NA))
        self$`code_version_snapshot` <- code_version_snapshotObject
      }
      if (!is.null(ModeldbProjectObject$`artifacts`)) {
        self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`date_created`)) {
        sprintf(
        '"date_created":
          "%s"
                ',
        self$`date_created`
        )},
        if (!is.null(self$`date_updated`)) {
        sprintf(
        '"date_updated":
          "%s"
                ',
        self$`date_updated`
        )},
        if (!is.null(self$`short_name`)) {
        sprintf(
        '"short_name":
          "%s"
                ',
        self$`short_name`
        )},
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )},
        if (!is.null(self$`project_visibility`)) {
        sprintf(
        '"project_visibility":
        %s
        ',
        jsonlite::toJSON(self$`project_visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`workspace_id`)) {
        sprintf(
        '"workspace_id":
          "%s"
                ',
        self$`workspace_id`
        )},
        if (!is.null(self$`workspace_type`)) {
        sprintf(
        '"workspace_type":
        %s
        ',
        jsonlite::toJSON(self$`workspace_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`workspace_service_id`)) {
        sprintf(
        '"workspace_service_id":
          "%s"
                ',
        self$`workspace_service_id`
        )},
        if (!is.null(self$`custom_permission`)) {
        sprintf(
        '"custom_permission":
        %s
        ',
        jsonlite::toJSON(self$`custom_permission`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`visibility`)) {
        sprintf(
        '"visibility":
        %s
        ',
        jsonlite::toJSON(self$`visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`owner`)) {
        sprintf(
        '"owner":
          "%s"
                ',
        self$`owner`
        )},
        if (!is.null(self$`code_version_snapshot`)) {
        sprintf(
        '"code_version_snapshot":
        %s
        ',
        jsonlite::toJSON(self$`code_version_snapshot`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`artifacts`)) {
        sprintf(
        '"artifacts":
        [%s]
',
        paste(sapply(self$`artifacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbProjectJson) {
      ModeldbProjectObject <- jsonlite::fromJSON(ModeldbProjectJson)
      self$`id` <- ModeldbProjectObject$`id`
      self$`name` <- ModeldbProjectObject$`name`
      self$`description` <- ModeldbProjectObject$`description`
      self$`date_created` <- ModeldbProjectObject$`date_created`
      self$`date_updated` <- ModeldbProjectObject$`date_updated`
      self$`short_name` <- ModeldbProjectObject$`short_name`
      self$`readme_text` <- ModeldbProjectObject$`readme_text`
      self$`project_visibility` <- ModeldbProjectVisibility$new()$fromJSON(jsonlite::toJSON(ModeldbProjectObject$project_visibility, auto_unbox = TRUE, digits = NA))
      self$`workspace_id` <- ModeldbProjectObject$`workspace_id`
      self$`workspace_type` <- WorkspaceTypeEnumWorkspaceType$new()$fromJSON(jsonlite::toJSON(ModeldbProjectObject$workspace_type, auto_unbox = TRUE, digits = NA))
      self$`workspace_service_id` <- ModeldbProjectObject$`workspace_service_id`
      self$`custom_permission` <- UacCollaboratorPermissions$new()$fromJSON(jsonlite::toJSON(ModeldbProjectObject$custom_permission, auto_unbox = TRUE, digits = NA))
      self$`visibility` <- UacResourceVisibility$new()$fromJSON(jsonlite::toJSON(ModeldbProjectObject$visibility, auto_unbox = TRUE, digits = NA))
      self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self$`tags` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`tags`, "array[character]", loadNamespace("openapi"))
      self$`owner` <- ModeldbProjectObject$`owner`
      self$`code_version_snapshot` <- ModeldbCodeVersion$new()$fromJSON(jsonlite::toJSON(ModeldbProjectObject$code_version_snapshot, auto_unbox = TRUE, digits = NA))
      self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbProjectObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      self
    }
  )
)

