# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbUpdateProjectName
#'
#' @description ModeldbUpdateProjectName Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbUpdateProjectName <- R6::R6Class(
  'ModeldbUpdateProjectName',
  public = list(
    `id` = NULL,
    `name` = NULL,
    initialize = function(
        `id`=NULL, `name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      ModeldbUpdateProjectNameObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbUpdateProjectNameObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ModeldbUpdateProjectNameObject[['name']] <-
          self$`name`
      }

      ModeldbUpdateProjectNameObject
    },
    fromJSON = function(ModeldbUpdateProjectNameJson) {
      ModeldbUpdateProjectNameObject <- jsonlite::fromJSON(ModeldbUpdateProjectNameJson)
      if (!is.null(ModeldbUpdateProjectNameObject$`id`)) {
        self$`id` <- ModeldbUpdateProjectNameObject$`id`
      }
      if (!is.null(ModeldbUpdateProjectNameObject$`name`)) {
        self$`name` <- ModeldbUpdateProjectNameObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbUpdateProjectNameJson) {
      ModeldbUpdateProjectNameObject <- jsonlite::fromJSON(ModeldbUpdateProjectNameJson)
      self$`id` <- ModeldbUpdateProjectNameObject$`id`
      self$`name` <- ModeldbUpdateProjectNameObject$`name`
      self
    }
  )
)

