# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeleteProjectResponse
#'
#' @description ModeldbDeleteProjectResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field status  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeleteProjectResponse <- R6::R6Class(
  'ModeldbDeleteProjectResponse',
  public = list(
    `status` = NULL,
    initialize = function(
        `status`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`status`)) {
        self$`status` <- `status`
      }
    },
    toJSON = function() {
      ModeldbDeleteProjectResponseObject <- list()
      if (!is.null(self$`status`)) {
        ModeldbDeleteProjectResponseObject[['status']] <-
          self$`status`
      }

      ModeldbDeleteProjectResponseObject
    },
    fromJSON = function(ModeldbDeleteProjectResponseJson) {
      ModeldbDeleteProjectResponseObject <- jsonlite::fromJSON(ModeldbDeleteProjectResponseJson)
      if (!is.null(ModeldbDeleteProjectResponseObject$`status`)) {
        self$`status` <- ModeldbDeleteProjectResponseObject$`status`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeleteProjectResponseJson) {
      ModeldbDeleteProjectResponseObject <- jsonlite::fromJSON(ModeldbDeleteProjectResponseJson)
      self$`status` <- ModeldbDeleteProjectResponseObject$`status`
      self
    }
  )
)

