# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbAddProjectTag
#'
#' @description ModeldbAddProjectTag Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field tag  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbAddProjectTag <- R6::R6Class(
  'ModeldbAddProjectTag',
  public = list(
    `id` = NULL,
    `tag` = NULL,
    initialize = function(
        `id`=NULL, `tag`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`tag`)) {
        stopifnot(is.character(`tag`), length(`tag`) == 1)
        self$`tag` <- `tag`
      }
    },
    toJSON = function() {
      ModeldbAddProjectTagObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbAddProjectTagObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`tag`)) {
        ModeldbAddProjectTagObject[['tag']] <-
          self$`tag`
      }

      ModeldbAddProjectTagObject
    },
    fromJSON = function(ModeldbAddProjectTagJson) {
      ModeldbAddProjectTagObject <- jsonlite::fromJSON(ModeldbAddProjectTagJson)
      if (!is.null(ModeldbAddProjectTagObject$`id`)) {
        self$`id` <- ModeldbAddProjectTagObject$`id`
      }
      if (!is.null(ModeldbAddProjectTagObject$`tag`)) {
        self$`tag` <- ModeldbAddProjectTagObject$`tag`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`tag`)) {
        sprintf(
        '"tag":
          "%s"
                ',
        self$`tag`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbAddProjectTagJson) {
      ModeldbAddProjectTagObject <- jsonlite::fromJSON(ModeldbAddProjectTagJson)
      self$`id` <- ModeldbAddProjectTagObject$`id`
      self$`tag` <- ModeldbAddProjectTagObject$`tag`
      self
    }
  )
)

