# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetProjectShortNameResponse
#'
#' @description ModeldbGetProjectShortNameResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field short_name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetProjectShortNameResponse <- R6::R6Class(
  'ModeldbGetProjectShortNameResponse',
  public = list(
    `short_name` = NULL,
    initialize = function(
        `short_name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`short_name`)) {
        stopifnot(is.character(`short_name`), length(`short_name`) == 1)
        self$`short_name` <- `short_name`
      }
    },
    toJSON = function() {
      ModeldbGetProjectShortNameResponseObject <- list()
      if (!is.null(self$`short_name`)) {
        ModeldbGetProjectShortNameResponseObject[['short_name']] <-
          self$`short_name`
      }

      ModeldbGetProjectShortNameResponseObject
    },
    fromJSON = function(ModeldbGetProjectShortNameResponseJson) {
      ModeldbGetProjectShortNameResponseObject <- jsonlite::fromJSON(ModeldbGetProjectShortNameResponseJson)
      if (!is.null(ModeldbGetProjectShortNameResponseObject$`short_name`)) {
        self$`short_name` <- ModeldbGetProjectShortNameResponseObject$`short_name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`short_name`)) {
        sprintf(
        '"short_name":
          "%s"
                ',
        self$`short_name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetProjectShortNameResponseJson) {
      ModeldbGetProjectShortNameResponseObject <- jsonlite::fromJSON(ModeldbGetProjectShortNameResponseJson)
      self$`short_name` <- ModeldbGetProjectShortNameResponseObject$`short_name`
      self
    }
  )
)

