# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGitSnapshot
#'
#' @description ModeldbGitSnapshot Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field filepaths  list( character ) [optional]
#'
#' @field repo  character [optional]
#'
#' @field hash  character [optional]
#'
#' @field is_dirty  \link{TernaryEnumTernary} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGitSnapshot <- R6::R6Class(
  'ModeldbGitSnapshot',
  public = list(
    `filepaths` = NULL,
    `repo` = NULL,
    `hash` = NULL,
    `is_dirty` = NULL,
    initialize = function(
        `filepaths`=NULL, `repo`=NULL, `hash`=NULL, `is_dirty`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`filepaths`)) {
        stopifnot(is.vector(`filepaths`), length(`filepaths`) != 0)
        sapply(`filepaths`, function(x) stopifnot(is.character(x)))
        self$`filepaths` <- `filepaths`
      }
      if (!is.null(`repo`)) {
        stopifnot(is.character(`repo`), length(`repo`) == 1)
        self$`repo` <- `repo`
      }
      if (!is.null(`hash`)) {
        stopifnot(is.character(`hash`), length(`hash`) == 1)
        self$`hash` <- `hash`
      }
      if (!is.null(`is_dirty`)) {
        stopifnot(R6::is.R6(`is_dirty`))
        self$`is_dirty` <- `is_dirty`
      }
    },
    toJSON = function() {
      ModeldbGitSnapshotObject <- list()
      if (!is.null(self$`filepaths`)) {
        ModeldbGitSnapshotObject[['filepaths']] <-
          self$`filepaths`
      }
      if (!is.null(self$`repo`)) {
        ModeldbGitSnapshotObject[['repo']] <-
          self$`repo`
      }
      if (!is.null(self$`hash`)) {
        ModeldbGitSnapshotObject[['hash']] <-
          self$`hash`
      }
      if (!is.null(self$`is_dirty`)) {
        ModeldbGitSnapshotObject[['is_dirty']] <-
          self$`is_dirty`$toJSON()
      }

      ModeldbGitSnapshotObject
    },
    fromJSON = function(ModeldbGitSnapshotJson) {
      ModeldbGitSnapshotObject <- jsonlite::fromJSON(ModeldbGitSnapshotJson)
      if (!is.null(ModeldbGitSnapshotObject$`filepaths`)) {
        self$`filepaths` <- ApiClient$new()$deserializeObj(ModeldbGitSnapshotObject$`filepaths`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbGitSnapshotObject$`repo`)) {
        self$`repo` <- ModeldbGitSnapshotObject$`repo`
      }
      if (!is.null(ModeldbGitSnapshotObject$`hash`)) {
        self$`hash` <- ModeldbGitSnapshotObject$`hash`
      }
      if (!is.null(ModeldbGitSnapshotObject$`is_dirty`)) {
        is_dirtyObject <- TernaryEnumTernary$new()
        is_dirtyObject$fromJSON(jsonlite::toJSON(ModeldbGitSnapshotObject$is_dirty, auto_unbox = TRUE, digits = NA))
        self$`is_dirty` <- is_dirtyObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`filepaths`)) {
        sprintf(
        '"filepaths":
           [%s]
        ',
        paste(unlist(lapply(self$`filepaths`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`repo`)) {
        sprintf(
        '"repo":
          "%s"
                ',
        self$`repo`
        )},
        if (!is.null(self$`hash`)) {
        sprintf(
        '"hash":
          "%s"
                ',
        self$`hash`
        )},
        if (!is.null(self$`is_dirty`)) {
        sprintf(
        '"is_dirty":
        %s
        ',
        jsonlite::toJSON(self$`is_dirty`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGitSnapshotJson) {
      ModeldbGitSnapshotObject <- jsonlite::fromJSON(ModeldbGitSnapshotJson)
      self$`filepaths` <- ApiClient$new()$deserializeObj(ModeldbGitSnapshotObject$`filepaths`, "array[character]", loadNamespace("openapi"))
      self$`repo` <- ModeldbGitSnapshotObject$`repo`
      self$`hash` <- ModeldbGitSnapshotObject$`hash`
      self$`is_dirty` <- TernaryEnumTernary$new()$fromJSON(jsonlite::toJSON(ModeldbGitSnapshotObject$is_dirty, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

