# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetArtifactsResponse
#'
#' @description ModeldbGetArtifactsResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field artifacts  list( \link{CommonArtifact} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetArtifactsResponse <- R6::R6Class(
  'ModeldbGetArtifactsResponse',
  public = list(
    `artifacts` = NULL,
    initialize = function(
        `artifacts`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`artifacts`)) {
        stopifnot(is.vector(`artifacts`), length(`artifacts`) != 0)
        sapply(`artifacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artifacts` <- `artifacts`
      }
    },
    toJSON = function() {
      ModeldbGetArtifactsResponseObject <- list()
      if (!is.null(self$`artifacts`)) {
        ModeldbGetArtifactsResponseObject[['artifacts']] <-
          lapply(self$`artifacts`, function(x) x$toJSON())
      }

      ModeldbGetArtifactsResponseObject
    },
    fromJSON = function(ModeldbGetArtifactsResponseJson) {
      ModeldbGetArtifactsResponseObject <- jsonlite::fromJSON(ModeldbGetArtifactsResponseJson)
      if (!is.null(ModeldbGetArtifactsResponseObject$`artifacts`)) {
        self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbGetArtifactsResponseObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`artifacts`)) {
        sprintf(
        '"artifacts":
        [%s]
',
        paste(sapply(self$`artifacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetArtifactsResponseJson) {
      ModeldbGetArtifactsResponseObject <- jsonlite::fromJSON(ModeldbGetArtifactsResponseJson)
      self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbGetArtifactsResponseObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      self
    }
  )
)

