# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeleteProjects
#'
#' @description ModeldbDeleteProjects Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ids  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeleteProjects <- R6::R6Class(
  'ModeldbDeleteProjects',
  public = list(
    `ids` = NULL,
    initialize = function(
        `ids`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`ids`)) {
        stopifnot(is.vector(`ids`), length(`ids`) != 0)
        sapply(`ids`, function(x) stopifnot(is.character(x)))
        self$`ids` <- `ids`
      }
    },
    toJSON = function() {
      ModeldbDeleteProjectsObject <- list()
      if (!is.null(self$`ids`)) {
        ModeldbDeleteProjectsObject[['ids']] <-
          self$`ids`
      }

      ModeldbDeleteProjectsObject
    },
    fromJSON = function(ModeldbDeleteProjectsJson) {
      ModeldbDeleteProjectsObject <- jsonlite::fromJSON(ModeldbDeleteProjectsJson)
      if (!is.null(ModeldbDeleteProjectsObject$`ids`)) {
        self$`ids` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectsObject$`ids`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ids`)) {
        sprintf(
        '"ids":
           [%s]
        ',
        paste(unlist(lapply(self$`ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeleteProjectsJson) {
      ModeldbDeleteProjectsObject <- jsonlite::fromJSON(ModeldbDeleteProjectsJson)
      self$`ids` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectsObject$`ids`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

