# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeleteProject
#'
#' @description ModeldbDeleteProject Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeleteProject <- R6::R6Class(
  'ModeldbDeleteProject',
  public = list(
    `id` = NULL,
    initialize = function(
        `id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      ModeldbDeleteProjectObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbDeleteProjectObject[['id']] <-
          self$`id`
      }

      ModeldbDeleteProjectObject
    },
    fromJSON = function(ModeldbDeleteProjectJson) {
      ModeldbDeleteProjectObject <- jsonlite::fromJSON(ModeldbDeleteProjectJson)
      if (!is.null(ModeldbDeleteProjectObject$`id`)) {
        self$`id` <- ModeldbDeleteProjectObject$`id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeleteProjectJson) {
      ModeldbDeleteProjectObject <- jsonlite::fromJSON(ModeldbDeleteProjectJson)
      self$`id` <- ModeldbDeleteProjectObject$`id`
      self
    }
  )
)

