# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbAddProjectTags
#'
#' @description ModeldbAddProjectTags Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbAddProjectTags <- R6::R6Class(
  'ModeldbAddProjectTags',
  public = list(
    `id` = NULL,
    `tags` = NULL,
    initialize = function(
        `id`=NULL, `tags`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      ModeldbAddProjectTagsObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbAddProjectTagsObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`tags`)) {
        ModeldbAddProjectTagsObject[['tags']] <-
          self$`tags`
      }

      ModeldbAddProjectTagsObject
    },
    fromJSON = function(ModeldbAddProjectTagsJson) {
      ModeldbAddProjectTagsObject <- jsonlite::fromJSON(ModeldbAddProjectTagsJson)
      if (!is.null(ModeldbAddProjectTagsObject$`id`)) {
        self$`id` <- ModeldbAddProjectTagsObject$`id`
      }
      if (!is.null(ModeldbAddProjectTagsObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ModeldbAddProjectTagsObject$`tags`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbAddProjectTagsJson) {
      ModeldbAddProjectTagsObject <- jsonlite::fromJSON(ModeldbAddProjectTagsJson)
      self$`id` <- ModeldbAddProjectTagsObject$`id`
      self$`tags` <- ApiClient$new()$deserializeObj(ModeldbAddProjectTagsObject$`tags`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

