# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetAttributesResponse
#'
#' @description ModeldbGetAttributesResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field attributes  list( \link{CommonKeyValue} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetAttributesResponse <- R6::R6Class(
  'ModeldbGetAttributesResponse',
  public = list(
    `attributes` = NULL,
    initialize = function(
        `attributes`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
    },
    toJSON = function() {
      ModeldbGetAttributesResponseObject <- list()
      if (!is.null(self$`attributes`)) {
        ModeldbGetAttributesResponseObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }

      ModeldbGetAttributesResponseObject
    },
    fromJSON = function(ModeldbGetAttributesResponseJson) {
      ModeldbGetAttributesResponseObject <- jsonlite::fromJSON(ModeldbGetAttributesResponseJson)
      if (!is.null(ModeldbGetAttributesResponseObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbGetAttributesResponseObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetAttributesResponseJson) {
      ModeldbGetAttributesResponseObject <- jsonlite::fromJSON(ModeldbGetAttributesResponseJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbGetAttributesResponseObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self
    }
  )
)

