# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetTagsResponse
#'
#' @description ModeldbGetTagsResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field tags  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetTagsResponse <- R6::R6Class(
  'ModeldbGetTagsResponse',
  public = list(
    `tags` = NULL,
    initialize = function(
        `tags`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      ModeldbGetTagsResponseObject <- list()
      if (!is.null(self$`tags`)) {
        ModeldbGetTagsResponseObject[['tags']] <-
          self$`tags`
      }

      ModeldbGetTagsResponseObject
    },
    fromJSON = function(ModeldbGetTagsResponseJson) {
      ModeldbGetTagsResponseObject <- jsonlite::fromJSON(ModeldbGetTagsResponseJson)
      if (!is.null(ModeldbGetTagsResponseObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ModeldbGetTagsResponseObject$`tags`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetTagsResponseJson) {
      ModeldbGetTagsResponseObject <- jsonlite::fromJSON(ModeldbGetTagsResponseJson)
      self$`tags` <- ApiClient$new()$deserializeObj(ModeldbGetTagsResponseObject$`tags`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

