# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetUrlForArtifactResponse
#'
#' @description ModeldbGetUrlForArtifactResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field url  character [optional]
#'
#' @field fields  named list( character ) [optional]
#'
#' @field multipart_upload_ok  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetUrlForArtifactResponse <- R6::R6Class(
  'ModeldbGetUrlForArtifactResponse',
  public = list(
    `url` = NULL,
    `fields` = NULL,
    `multipart_upload_ok` = NULL,
    initialize = function(
        `url`=NULL, `fields`=NULL, `multipart_upload_ok`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`fields`)) {
        stopifnot(is.vector(`fields`), length(`fields`) != 0)
        sapply(`fields`, function(x) stopifnot(is.character(x)))
        self$`fields` <- `fields`
      }
      if (!is.null(`multipart_upload_ok`)) {
        self$`multipart_upload_ok` <- `multipart_upload_ok`
      }
    },
    toJSON = function() {
      ModeldbGetUrlForArtifactResponseObject <- list()
      if (!is.null(self$`url`)) {
        ModeldbGetUrlForArtifactResponseObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`fields`)) {
        ModeldbGetUrlForArtifactResponseObject[['fields']] <-
          self$`fields`
      }
      if (!is.null(self$`multipart_upload_ok`)) {
        ModeldbGetUrlForArtifactResponseObject[['multipart_upload_ok']] <-
          self$`multipart_upload_ok`
      }

      ModeldbGetUrlForArtifactResponseObject
    },
    fromJSON = function(ModeldbGetUrlForArtifactResponseJson) {
      ModeldbGetUrlForArtifactResponseObject <- jsonlite::fromJSON(ModeldbGetUrlForArtifactResponseJson)
      if (!is.null(ModeldbGetUrlForArtifactResponseObject$`url`)) {
        self$`url` <- ModeldbGetUrlForArtifactResponseObject$`url`
      }
      if (!is.null(ModeldbGetUrlForArtifactResponseObject$`fields`)) {
        self$`fields` <- ApiClient$new()$deserializeObj(ModeldbGetUrlForArtifactResponseObject$`fields`, "map(character)", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbGetUrlForArtifactResponseObject$`multipart_upload_ok`)) {
        self$`multipart_upload_ok` <- ModeldbGetUrlForArtifactResponseObject$`multipart_upload_ok`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`fields`)) {
        sprintf(
        '"fields":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`fields`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`multipart_upload_ok`)) {
        sprintf(
        '"multipart_upload_ok":
          "%s"
                ',
        self$`multipart_upload_ok`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetUrlForArtifactResponseJson) {
      ModeldbGetUrlForArtifactResponseObject <- jsonlite::fromJSON(ModeldbGetUrlForArtifactResponseJson)
      self$`url` <- ModeldbGetUrlForArtifactResponseObject$`url`
      self$`fields` <- ApiClient$new()$deserializeObj(ModeldbGetUrlForArtifactResponseObject$`fields`, "map(character)", loadNamespace("openapi"))
      self$`multipart_upload_ok` <- ModeldbGetUrlForArtifactResponseObject$`multipart_upload_ok`
      self
    }
  )
)

