# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbLogProjectCodeVersion
#'
#' @description ModeldbLogProjectCodeVersion Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field code_version  \link{ModeldbCodeVersion} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbLogProjectCodeVersion <- R6::R6Class(
  'ModeldbLogProjectCodeVersion',
  public = list(
    `id` = NULL,
    `code_version` = NULL,
    initialize = function(
        `id`=NULL, `code_version`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`code_version`)) {
        stopifnot(R6::is.R6(`code_version`))
        self$`code_version` <- `code_version`
      }
    },
    toJSON = function() {
      ModeldbLogProjectCodeVersionObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbLogProjectCodeVersionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`code_version`)) {
        ModeldbLogProjectCodeVersionObject[['code_version']] <-
          self$`code_version`$toJSON()
      }

      ModeldbLogProjectCodeVersionObject
    },
    fromJSON = function(ModeldbLogProjectCodeVersionJson) {
      ModeldbLogProjectCodeVersionObject <- jsonlite::fromJSON(ModeldbLogProjectCodeVersionJson)
      if (!is.null(ModeldbLogProjectCodeVersionObject$`id`)) {
        self$`id` <- ModeldbLogProjectCodeVersionObject$`id`
      }
      if (!is.null(ModeldbLogProjectCodeVersionObject$`code_version`)) {
        code_versionObject <- ModeldbCodeVersion$new()
        code_versionObject$fromJSON(jsonlite::toJSON(ModeldbLogProjectCodeVersionObject$code_version, auto_unbox = TRUE, digits = NA))
        self$`code_version` <- code_versionObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`code_version`)) {
        sprintf(
        '"code_version":
        %s
        ',
        jsonlite::toJSON(self$`code_version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbLogProjectCodeVersionJson) {
      ModeldbLogProjectCodeVersionObject <- jsonlite::fromJSON(ModeldbLogProjectCodeVersionJson)
      self$`id` <- ModeldbLogProjectCodeVersionObject$`id`
      self$`code_version` <- ModeldbCodeVersion$new()$fromJSON(jsonlite::toJSON(ModeldbLogProjectCodeVersionObject$code_version, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

