# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbCreateProject
#'
#' @description ModeldbCreateProject Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field description  character [optional]
#'
#' @field attributes  list( \link{CommonKeyValue} ) [optional]
#'
#' @field tags  list( character ) [optional]
#'
#' @field readme_text  character [optional]
#'
#' @field project_visibility  \link{ModeldbProjectVisibility} [optional]
#'
#' @field artifacts  list( \link{CommonArtifact} ) [optional]
#'
#' @field workspace_name  character [optional]
#'
#' @field date_created  character [optional]
#'
#' @field custom_permission  \link{UacCollaboratorPermissions} [optional]
#'
#' @field visibility  \link{UacResourceVisibility} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbCreateProject <- R6::R6Class(
  'ModeldbCreateProject',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `attributes` = NULL,
    `tags` = NULL,
    `readme_text` = NULL,
    `project_visibility` = NULL,
    `artifacts` = NULL,
    `workspace_name` = NULL,
    `date_created` = NULL,
    `custom_permission` = NULL,
    `visibility` = NULL,
    initialize = function(
        `name`=NULL, `description`=NULL, `attributes`=NULL, `tags`=NULL, `readme_text`=NULL, `project_visibility`=NULL, `artifacts`=NULL, `workspace_name`=NULL, `date_created`=NULL, `custom_permission`=NULL, `visibility`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`tags`)) {
        stopifnot(is.vector(`tags`), length(`tags`) != 0)
        sapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
      if (!is.null(`project_visibility`)) {
        stopifnot(R6::is.R6(`project_visibility`))
        self$`project_visibility` <- `project_visibility`
      }
      if (!is.null(`artifacts`)) {
        stopifnot(is.vector(`artifacts`), length(`artifacts`) != 0)
        sapply(`artifacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artifacts` <- `artifacts`
      }
      if (!is.null(`workspace_name`)) {
        stopifnot(is.character(`workspace_name`), length(`workspace_name`) == 1)
        self$`workspace_name` <- `workspace_name`
      }
      if (!is.null(`date_created`)) {
        stopifnot(is.character(`date_created`), length(`date_created`) == 1)
        self$`date_created` <- `date_created`
      }
      if (!is.null(`custom_permission`)) {
        stopifnot(R6::is.R6(`custom_permission`))
        self$`custom_permission` <- `custom_permission`
      }
      if (!is.null(`visibility`)) {
        stopifnot(R6::is.R6(`visibility`))
        self$`visibility` <- `visibility`
      }
    },
    toJSON = function() {
      ModeldbCreateProjectObject <- list()
      if (!is.null(self$`name`)) {
        ModeldbCreateProjectObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`description`)) {
        ModeldbCreateProjectObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`attributes`)) {
        ModeldbCreateProjectObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`tags`)) {
        ModeldbCreateProjectObject[['tags']] <-
          self$`tags`
      }
      if (!is.null(self$`readme_text`)) {
        ModeldbCreateProjectObject[['readme_text']] <-
          self$`readme_text`
      }
      if (!is.null(self$`project_visibility`)) {
        ModeldbCreateProjectObject[['project_visibility']] <-
          self$`project_visibility`$toJSON()
      }
      if (!is.null(self$`artifacts`)) {
        ModeldbCreateProjectObject[['artifacts']] <-
          lapply(self$`artifacts`, function(x) x$toJSON())
      }
      if (!is.null(self$`workspace_name`)) {
        ModeldbCreateProjectObject[['workspace_name']] <-
          self$`workspace_name`
      }
      if (!is.null(self$`date_created`)) {
        ModeldbCreateProjectObject[['date_created']] <-
          self$`date_created`
      }
      if (!is.null(self$`custom_permission`)) {
        ModeldbCreateProjectObject[['custom_permission']] <-
          self$`custom_permission`$toJSON()
      }
      if (!is.null(self$`visibility`)) {
        ModeldbCreateProjectObject[['visibility']] <-
          self$`visibility`$toJSON()
      }

      ModeldbCreateProjectObject
    },
    fromJSON = function(ModeldbCreateProjectJson) {
      ModeldbCreateProjectObject <- jsonlite::fromJSON(ModeldbCreateProjectJson)
      if (!is.null(ModeldbCreateProjectObject$`name`)) {
        self$`name` <- ModeldbCreateProjectObject$`name`
      }
      if (!is.null(ModeldbCreateProjectObject$`description`)) {
        self$`description` <- ModeldbCreateProjectObject$`description`
      }
      if (!is.null(ModeldbCreateProjectObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbCreateProjectObject$`tags`)) {
        self$`tags` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`tags`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbCreateProjectObject$`readme_text`)) {
        self$`readme_text` <- ModeldbCreateProjectObject$`readme_text`
      }
      if (!is.null(ModeldbCreateProjectObject$`project_visibility`)) {
        project_visibilityObject <- ModeldbProjectVisibility$new()
        project_visibilityObject$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$project_visibility, auto_unbox = TRUE, digits = NA))
        self$`project_visibility` <- project_visibilityObject
      }
      if (!is.null(ModeldbCreateProjectObject$`artifacts`)) {
        self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbCreateProjectObject$`workspace_name`)) {
        self$`workspace_name` <- ModeldbCreateProjectObject$`workspace_name`
      }
      if (!is.null(ModeldbCreateProjectObject$`date_created`)) {
        self$`date_created` <- ModeldbCreateProjectObject$`date_created`
      }
      if (!is.null(ModeldbCreateProjectObject$`custom_permission`)) {
        custom_permissionObject <- UacCollaboratorPermissions$new()
        custom_permissionObject$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$custom_permission, auto_unbox = TRUE, digits = NA))
        self$`custom_permission` <- custom_permissionObject
      }
      if (!is.null(ModeldbCreateProjectObject$`visibility`)) {
        visibilityObject <- UacResourceVisibility$new()
        visibilityObject$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$visibility, auto_unbox = TRUE, digits = NA))
        self$`visibility` <- visibilityObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`tags`)) {
        sprintf(
        '"tags":
           [%s]
        ',
        paste(unlist(lapply(self$`tags`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )},
        if (!is.null(self$`project_visibility`)) {
        sprintf(
        '"project_visibility":
        %s
        ',
        jsonlite::toJSON(self$`project_visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`artifacts`)) {
        sprintf(
        '"artifacts":
        [%s]
',
        paste(sapply(self$`artifacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`workspace_name`)) {
        sprintf(
        '"workspace_name":
          "%s"
                ',
        self$`workspace_name`
        )},
        if (!is.null(self$`date_created`)) {
        sprintf(
        '"date_created":
          "%s"
                ',
        self$`date_created`
        )},
        if (!is.null(self$`custom_permission`)) {
        sprintf(
        '"custom_permission":
        %s
        ',
        jsonlite::toJSON(self$`custom_permission`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`visibility`)) {
        sprintf(
        '"visibility":
        %s
        ',
        jsonlite::toJSON(self$`visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbCreateProjectJson) {
      ModeldbCreateProjectObject <- jsonlite::fromJSON(ModeldbCreateProjectJson)
      self$`name` <- ModeldbCreateProjectObject$`name`
      self$`description` <- ModeldbCreateProjectObject$`description`
      self$`attributes` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self$`tags` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`tags`, "array[character]", loadNamespace("openapi"))
      self$`readme_text` <- ModeldbCreateProjectObject$`readme_text`
      self$`project_visibility` <- ModeldbProjectVisibility$new()$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$project_visibility, auto_unbox = TRUE, digits = NA))
      self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbCreateProjectObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      self$`workspace_name` <- ModeldbCreateProjectObject$`workspace_name`
      self$`date_created` <- ModeldbCreateProjectObject$`date_created`
      self$`custom_permission` <- UacCollaboratorPermissions$new()$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$custom_permission, auto_unbox = TRUE, digits = NA))
      self$`visibility` <- UacResourceVisibility$new()$fromJSON(jsonlite::toJSON(ModeldbCreateProjectObject$visibility, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

