# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeleteProjectAttributes
#'
#' @description ModeldbDeleteProjectAttributes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field attribute_keys  list( character ) [optional]
#'
#' @field delete_all  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeleteProjectAttributes <- R6::R6Class(
  'ModeldbDeleteProjectAttributes',
  public = list(
    `id` = NULL,
    `attribute_keys` = NULL,
    `delete_all` = NULL,
    initialize = function(
        `id`=NULL, `attribute_keys`=NULL, `delete_all`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`attribute_keys`)) {
        stopifnot(is.vector(`attribute_keys`), length(`attribute_keys`) != 0)
        sapply(`attribute_keys`, function(x) stopifnot(is.character(x)))
        self$`attribute_keys` <- `attribute_keys`
      }
      if (!is.null(`delete_all`)) {
        self$`delete_all` <- `delete_all`
      }
    },
    toJSON = function() {
      ModeldbDeleteProjectAttributesObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbDeleteProjectAttributesObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`attribute_keys`)) {
        ModeldbDeleteProjectAttributesObject[['attribute_keys']] <-
          self$`attribute_keys`
      }
      if (!is.null(self$`delete_all`)) {
        ModeldbDeleteProjectAttributesObject[['delete_all']] <-
          self$`delete_all`
      }

      ModeldbDeleteProjectAttributesObject
    },
    fromJSON = function(ModeldbDeleteProjectAttributesJson) {
      ModeldbDeleteProjectAttributesObject <- jsonlite::fromJSON(ModeldbDeleteProjectAttributesJson)
      if (!is.null(ModeldbDeleteProjectAttributesObject$`id`)) {
        self$`id` <- ModeldbDeleteProjectAttributesObject$`id`
      }
      if (!is.null(ModeldbDeleteProjectAttributesObject$`attribute_keys`)) {
        self$`attribute_keys` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectAttributesObject$`attribute_keys`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(ModeldbDeleteProjectAttributesObject$`delete_all`)) {
        self$`delete_all` <- ModeldbDeleteProjectAttributesObject$`delete_all`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`attribute_keys`)) {
        sprintf(
        '"attribute_keys":
           [%s]
        ',
        paste(unlist(lapply(self$`attribute_keys`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`delete_all`)) {
        sprintf(
        '"delete_all":
          "%s"
                ',
        self$`delete_all`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeleteProjectAttributesJson) {
      ModeldbDeleteProjectAttributesObject <- jsonlite::fromJSON(ModeldbDeleteProjectAttributesJson)
      self$`id` <- ModeldbDeleteProjectAttributesObject$`id`
      self$`attribute_keys` <- ApiClient$new()$deserializeObj(ModeldbDeleteProjectAttributesObject$`attribute_keys`, "array[character]", loadNamespace("openapi"))
      self$`delete_all` <- ModeldbDeleteProjectAttributesObject$`delete_all`
      self
    }
  )
)

