# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbUpdateProjectDescription
#'
#' @description ModeldbUpdateProjectDescription Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field description  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbUpdateProjectDescription <- R6::R6Class(
  'ModeldbUpdateProjectDescription',
  public = list(
    `id` = NULL,
    `description` = NULL,
    initialize = function(
        `id`=NULL, `description`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      ModeldbUpdateProjectDescriptionObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbUpdateProjectDescriptionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`description`)) {
        ModeldbUpdateProjectDescriptionObject[['description']] <-
          self$`description`
      }

      ModeldbUpdateProjectDescriptionObject
    },
    fromJSON = function(ModeldbUpdateProjectDescriptionJson) {
      ModeldbUpdateProjectDescriptionObject <- jsonlite::fromJSON(ModeldbUpdateProjectDescriptionJson)
      if (!is.null(ModeldbUpdateProjectDescriptionObject$`id`)) {
        self$`id` <- ModeldbUpdateProjectDescriptionObject$`id`
      }
      if (!is.null(ModeldbUpdateProjectDescriptionObject$`description`)) {
        self$`description` <- ModeldbUpdateProjectDescriptionObject$`description`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbUpdateProjectDescriptionJson) {
      ModeldbUpdateProjectDescriptionObject <- jsonlite::fromJSON(ModeldbUpdateProjectDescriptionJson)
      self$`id` <- ModeldbUpdateProjectDescriptionObject$`id`
      self$`description` <- ModeldbUpdateProjectDescriptionObject$`description`
      self
    }
  )
)

