# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbMetricsSummary
#'
#' @description ModeldbMetricsSummary Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field key  character [optional]
#'
#' @field min_value  numeric [optional]
#'
#' @field max_value  numeric [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbMetricsSummary <- R6::R6Class(
  'ModeldbMetricsSummary',
  public = list(
    `key` = NULL,
    `min_value` = NULL,
    `max_value` = NULL,
    initialize = function(
        `key`=NULL, `min_value`=NULL, `max_value`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`min_value`)) {
        stopifnot(is.numeric(`min_value`), length(`min_value`) == 1)
        self$`min_value` <- `min_value`
      }
      if (!is.null(`max_value`)) {
        stopifnot(is.numeric(`max_value`), length(`max_value`) == 1)
        self$`max_value` <- `max_value`
      }
    },
    toJSON = function() {
      ModeldbMetricsSummaryObject <- list()
      if (!is.null(self$`key`)) {
        ModeldbMetricsSummaryObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`min_value`)) {
        ModeldbMetricsSummaryObject[['min_value']] <-
          self$`min_value`
      }
      if (!is.null(self$`max_value`)) {
        ModeldbMetricsSummaryObject[['max_value']] <-
          self$`max_value`
      }

      ModeldbMetricsSummaryObject
    },
    fromJSON = function(ModeldbMetricsSummaryJson) {
      ModeldbMetricsSummaryObject <- jsonlite::fromJSON(ModeldbMetricsSummaryJson)
      if (!is.null(ModeldbMetricsSummaryObject$`key`)) {
        self$`key` <- ModeldbMetricsSummaryObject$`key`
      }
      if (!is.null(ModeldbMetricsSummaryObject$`min_value`)) {
        self$`min_value` <- ModeldbMetricsSummaryObject$`min_value`
      }
      if (!is.null(ModeldbMetricsSummaryObject$`max_value`)) {
        self$`max_value` <- ModeldbMetricsSummaryObject$`max_value`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`min_value`)) {
        sprintf(
        '"min_value":
          %d
                ',
        self$`min_value`
        )},
        if (!is.null(self$`max_value`)) {
        sprintf(
        '"max_value":
          %d
                ',
        self$`max_value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbMetricsSummaryJson) {
      ModeldbMetricsSummaryObject <- jsonlite::fromJSON(ModeldbMetricsSummaryJson)
      self$`key` <- ModeldbMetricsSummaryObject$`key`
      self$`min_value` <- ModeldbMetricsSummaryObject$`min_value`
      self$`max_value` <- ModeldbMetricsSummaryObject$`max_value`
      self
    }
  )
)

