# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbDeepCopyProject
#'
#' @description ModeldbDeepCopyProject Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbDeepCopyProject <- R6::R6Class(
  'ModeldbDeepCopyProject',
  public = list(
    `id` = NULL,
    initialize = function(
        `id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      ModeldbDeepCopyProjectObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbDeepCopyProjectObject[['id']] <-
          self$`id`
      }

      ModeldbDeepCopyProjectObject
    },
    fromJSON = function(ModeldbDeepCopyProjectJson) {
      ModeldbDeepCopyProjectObject <- jsonlite::fromJSON(ModeldbDeepCopyProjectJson)
      if (!is.null(ModeldbDeepCopyProjectObject$`id`)) {
        self$`id` <- ModeldbDeepCopyProjectObject$`id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbDeepCopyProjectJson) {
      ModeldbDeepCopyProjectObject <- jsonlite::fromJSON(ModeldbDeepCopyProjectJson)
      self$`id` <- ModeldbDeepCopyProjectObject$`id`
      self
    }
  )
)

