# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbSetProjectShortName
#'
#' @description ModeldbSetProjectShortName Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field short_name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbSetProjectShortName <- R6::R6Class(
  'ModeldbSetProjectShortName',
  public = list(
    `id` = NULL,
    `short_name` = NULL,
    initialize = function(
        `id`=NULL, `short_name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`short_name`)) {
        stopifnot(is.character(`short_name`), length(`short_name`) == 1)
        self$`short_name` <- `short_name`
      }
    },
    toJSON = function() {
      ModeldbSetProjectShortNameObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbSetProjectShortNameObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`short_name`)) {
        ModeldbSetProjectShortNameObject[['short_name']] <-
          self$`short_name`
      }

      ModeldbSetProjectShortNameObject
    },
    fromJSON = function(ModeldbSetProjectShortNameJson) {
      ModeldbSetProjectShortNameObject <- jsonlite::fromJSON(ModeldbSetProjectShortNameJson)
      if (!is.null(ModeldbSetProjectShortNameObject$`id`)) {
        self$`id` <- ModeldbSetProjectShortNameObject$`id`
      }
      if (!is.null(ModeldbSetProjectShortNameObject$`short_name`)) {
        self$`short_name` <- ModeldbSetProjectShortNameObject$`short_name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`short_name`)) {
        sprintf(
        '"short_name":
          "%s"
                ',
        self$`short_name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbSetProjectShortNameJson) {
      ModeldbSetProjectShortNameObject <- jsonlite::fromJSON(ModeldbSetProjectShortNameJson)
      self$`id` <- ModeldbSetProjectShortNameObject$`id`
      self$`short_name` <- ModeldbSetProjectShortNameObject$`short_name`
      self
    }
  )
)

