# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbLogProjectArtifacts
#'
#' @description ModeldbLogProjectArtifacts Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field artifacts  list( \link{CommonArtifact} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbLogProjectArtifacts <- R6::R6Class(
  'ModeldbLogProjectArtifacts',
  public = list(
    `id` = NULL,
    `artifacts` = NULL,
    initialize = function(
        `id`=NULL, `artifacts`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`artifacts`)) {
        stopifnot(is.vector(`artifacts`), length(`artifacts`) != 0)
        sapply(`artifacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artifacts` <- `artifacts`
      }
    },
    toJSON = function() {
      ModeldbLogProjectArtifactsObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbLogProjectArtifactsObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`artifacts`)) {
        ModeldbLogProjectArtifactsObject[['artifacts']] <-
          lapply(self$`artifacts`, function(x) x$toJSON())
      }

      ModeldbLogProjectArtifactsObject
    },
    fromJSON = function(ModeldbLogProjectArtifactsJson) {
      ModeldbLogProjectArtifactsObject <- jsonlite::fromJSON(ModeldbLogProjectArtifactsJson)
      if (!is.null(ModeldbLogProjectArtifactsObject$`id`)) {
        self$`id` <- ModeldbLogProjectArtifactsObject$`id`
      }
      if (!is.null(ModeldbLogProjectArtifactsObject$`artifacts`)) {
        self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbLogProjectArtifactsObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`artifacts`)) {
        sprintf(
        '"artifacts":
        [%s]
',
        paste(sapply(self$`artifacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbLogProjectArtifactsJson) {
      ModeldbLogProjectArtifactsObject <- jsonlite::fromJSON(ModeldbLogProjectArtifactsJson)
      self$`id` <- ModeldbLogProjectArtifactsObject$`id`
      self$`artifacts` <- ApiClient$new()$deserializeObj(ModeldbLogProjectArtifactsObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      self
    }
  )
)

