# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbGetProjectReadmeResponse
#'
#' @description ModeldbGetProjectReadmeResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field readme_text  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbGetProjectReadmeResponse <- R6::R6Class(
  'ModeldbGetProjectReadmeResponse',
  public = list(
    `readme_text` = NULL,
    initialize = function(
        `readme_text`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
    },
    toJSON = function() {
      ModeldbGetProjectReadmeResponseObject <- list()
      if (!is.null(self$`readme_text`)) {
        ModeldbGetProjectReadmeResponseObject[['readme_text']] <-
          self$`readme_text`
      }

      ModeldbGetProjectReadmeResponseObject
    },
    fromJSON = function(ModeldbGetProjectReadmeResponseJson) {
      ModeldbGetProjectReadmeResponseObject <- jsonlite::fromJSON(ModeldbGetProjectReadmeResponseJson)
      if (!is.null(ModeldbGetProjectReadmeResponseObject$`readme_text`)) {
        self$`readme_text` <- ModeldbGetProjectReadmeResponseObject$`readme_text`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbGetProjectReadmeResponseJson) {
      ModeldbGetProjectReadmeResponseObject <- jsonlite::fromJSON(ModeldbGetProjectReadmeResponseJson)
      self$`readme_text` <- ModeldbGetProjectReadmeResponseObject$`readme_text`
      self
    }
  )
)

