# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModeldbUpdateProjectAttributes
#'
#' @description ModeldbUpdateProjectAttributes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field attribute  \link{CommonKeyValue} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldbUpdateProjectAttributes <- R6::R6Class(
  'ModeldbUpdateProjectAttributes',
  public = list(
    `id` = NULL,
    `attribute` = NULL,
    initialize = function(
        `id`=NULL, `attribute`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`attribute`)) {
        stopifnot(R6::is.R6(`attribute`))
        self$`attribute` <- `attribute`
      }
    },
    toJSON = function() {
      ModeldbUpdateProjectAttributesObject <- list()
      if (!is.null(self$`id`)) {
        ModeldbUpdateProjectAttributesObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`attribute`)) {
        ModeldbUpdateProjectAttributesObject[['attribute']] <-
          self$`attribute`$toJSON()
      }

      ModeldbUpdateProjectAttributesObject
    },
    fromJSON = function(ModeldbUpdateProjectAttributesJson) {
      ModeldbUpdateProjectAttributesObject <- jsonlite::fromJSON(ModeldbUpdateProjectAttributesJson)
      if (!is.null(ModeldbUpdateProjectAttributesObject$`id`)) {
        self$`id` <- ModeldbUpdateProjectAttributesObject$`id`
      }
      if (!is.null(ModeldbUpdateProjectAttributesObject$`attribute`)) {
        attributeObject <- CommonKeyValue$new()
        attributeObject$fromJSON(jsonlite::toJSON(ModeldbUpdateProjectAttributesObject$attribute, auto_unbox = TRUE, digits = NA))
        self$`attribute` <- attributeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`attribute`)) {
        sprintf(
        '"attribute":
        %s
        ',
        jsonlite::toJSON(self$`attribute`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ModeldbUpdateProjectAttributesJson) {
      ModeldbUpdateProjectAttributesObject <- jsonlite::fromJSON(ModeldbUpdateProjectAttributesJson)
      self$`id` <- ModeldbUpdateProjectAttributesObject$`id`
      self$`attribute` <- CommonKeyValue$new()$fromJSON(jsonlite::toJSON(ModeldbUpdateProjectAttributesObject$attribute, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

