# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
#
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProjectService operations
#' @description openapi.ProjectService
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ ProjectServiceAddProjectAttributes } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbAddProjectAttributes}
#' \item \emph{ @returnType } \link{ModeldbAddProjectAttributesResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbAddProjectAttributesResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceAddProjectTag } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbAddProjectTag}
#' \item \emph{ @returnType } \link{ModeldbAddProjectTagResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbAddProjectTagResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceAddProjectTags } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbAddProjectTags}
#' \item \emph{ @returnType } \link{ModeldbAddProjectTagsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbAddProjectTagsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceCreateProject } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbCreateProject}
#' \item \emph{ @returnType } \link{ModeldbCreateProjectResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbCreateProjectResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeepCopyProject } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeepCopyProject}
#' \item \emph{ @returnType } \link{ModeldbDeepCopyProjectResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeepCopyProjectResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteArtifact } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProjectArtifact}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectArtifactResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectArtifactResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteProject } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProject}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteProjectAttributes } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProjectAttributes}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectAttributesResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectAttributesResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteProjectTag } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProjectTag}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectTagResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectTagResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteProjectTags } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProjectTags}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectTagsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectTagsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceDeleteProjects } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbDeleteProjects}
#' \item \emph{ @returnType } \link{ModeldbDeleteProjectsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbDeleteProjectsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceFindProjects } \emph{ queries }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbFindProjects}
#' \item \emph{ @returnType } \link{ModeldbFindProjectsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbFindProjectsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetArtifacts } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } key character
#' \item \emph{ @returnType } \link{ModeldbGetArtifactsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetArtifactsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectAttributes } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } attribute.keys list( character )
#' \item \emph{ @param } get.all character
#' \item \emph{ @returnType } \link{ModeldbGetAttributesResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetAttributesResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectById } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{ModeldbGetProjectByIdResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectByIdResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectByName } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } name character
#' \item \emph{ @param } workspace.name character
#' \item \emph{ @returnType } \link{ModeldbGetProjectByNameResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectByNameResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectCodeVersion } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{ModeldbGetProjectCodeVersionResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectCodeVersionResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectDatasetCount } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } project.id character
#' \item \emph{ @returnType } \link{ModeldbGetProjectDatasetCountResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectDatasetCountResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectReadme } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{ModeldbGetProjectReadmeResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectReadmeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectShortName } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{ModeldbGetProjectShortNameResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectShortNameResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjectTags } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{ModeldbGetTagsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetTagsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetProjects } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } page.number integer
#' \item \emph{ @param } page.limit integer
#' \item \emph{ @param } ascending character
#' \item \emph{ @param } sort.key character
#' \item \emph{ @param } workspace.name character
#' \item \emph{ @returnType } \link{ModeldbGetProjectsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetProjectsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetSummary } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } entity.id character
#' \item \emph{ @returnType } \link{ModeldbGetSummaryResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetSummaryResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceGetUrlForArtifact } \emph{ artifacts }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbGetUrlForArtifact}
#' \item \emph{ @returnType } \link{ModeldbGetUrlForArtifactResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbGetUrlForArtifactResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceLogArtifacts } \emph{ artifacts }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbLogProjectArtifacts}
#' \item \emph{ @returnType } \link{ModeldbLogProjectArtifactsResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbLogProjectArtifactsResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceLogProjectCodeVersion } \emph{ code version }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbLogProjectCodeVersion}
#' \item \emph{ @returnType } \link{ModeldbLogProjectCodeVersionResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbLogProjectCodeVersionResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceSetProjectReadme } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbSetProjectReadme}
#' \item \emph{ @returnType } \link{ModeldbSetProjectReadmeResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbSetProjectReadmeResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceSetProjectShortName } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbSetProjectShortName}
#' \item \emph{ @returnType } \link{ModeldbSetProjectShortNameResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbSetProjectShortNameResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceUpdateProjectAttributes } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbUpdateProjectAttributes}
#' \item \emph{ @returnType } \link{ModeldbUpdateProjectAttributesResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbUpdateProjectAttributesResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceUpdateProjectDescription } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbUpdateProjectDescription}
#' \item \emph{ @returnType } \link{ModeldbUpdateProjectDescriptionResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbUpdateProjectDescriptionResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceUpdateProjectName } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @param } body \link{ModeldbUpdateProjectName}
#' \item \emph{ @returnType } \link{ModeldbUpdateProjectNameResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbUpdateProjectNameResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ProjectServiceVerifyConnection } \emph{  }
#'
#'
#' \itemize{
#' \item \emph{ @returnType } \link{ModeldbVerifyConnectionResponse} \cr
#'
#'
#' \item status code : 200 | A successful response.
#'
#' \item return type : ModeldbVerifyConnectionResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 0 | An unexpected error response
#'
#' \item return type : RuntimeError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  ProjectServiceAddProjectAttributes  ####################
#'
#' library(openapi)
#' var.body <- ModeldbAddProjectAttributes$new() # ModeldbAddProjectAttributes |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceAddProjectAttributes(var.body)
#'
#'
#' ####################  ProjectServiceAddProjectTag  ####################
#'
#' library(openapi)
#' var.body <- ModeldbAddProjectTag$new() # ModeldbAddProjectTag |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceAddProjectTag(var.body)
#'
#'
#' ####################  ProjectServiceAddProjectTags  ####################
#'
#' library(openapi)
#' var.body <- ModeldbAddProjectTags$new() # ModeldbAddProjectTags |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceAddProjectTags(var.body)
#'
#'
#' ####################  ProjectServiceCreateProject  ####################
#'
#' library(openapi)
#' var.body <- ModeldbCreateProject$new() # ModeldbCreateProject |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceCreateProject(var.body)
#'
#'
#' ####################  ProjectServiceDeepCopyProject  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeepCopyProject$new() # ModeldbDeepCopyProject |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeepCopyProject(var.body)
#'
#'
#' ####################  ProjectServiceDeleteArtifact  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProjectArtifact$new() # ModeldbDeleteProjectArtifact |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteArtifact(var.body)
#'
#'
#' ####################  ProjectServiceDeleteProject  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProject$new() # ModeldbDeleteProject |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteProject(var.body)
#'
#'
#' ####################  ProjectServiceDeleteProjectAttributes  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProjectAttributes$new() # ModeldbDeleteProjectAttributes |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteProjectAttributes(var.body)
#'
#'
#' ####################  ProjectServiceDeleteProjectTag  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProjectTag$new() # ModeldbDeleteProjectTag |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteProjectTag(var.body)
#'
#'
#' ####################  ProjectServiceDeleteProjectTags  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProjectTags$new() # ModeldbDeleteProjectTags |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteProjectTags(var.body)
#'
#'
#' ####################  ProjectServiceDeleteProjects  ####################
#'
#' library(openapi)
#' var.body <- ModeldbDeleteProjects$new() # ModeldbDeleteProjects |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceDeleteProjects(var.body)
#'
#'
#' ####################  ProjectServiceFindProjects  ####################
#'
#' library(openapi)
#' var.body <- ModeldbFindProjects$new() # ModeldbFindProjects |
#'
#' #queries
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceFindProjects(var.body)
#'
#'
#' ####################  ProjectServiceGetArtifacts  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#' var.key <- 'key_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetArtifacts(id=var.id, key=var.key)
#'
#'
#' ####################  ProjectServiceGetProjectAttributes  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#' var.attribute.keys <- ['attribute.keys_example'] # array[character] |
#' var.get.all <- 'get.all_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectAttributes(id=var.id, attribute.keys=var.attribute.keys, get.all=var.get.all)
#'
#'
#' ####################  ProjectServiceGetProjectById  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectById(id=var.id)
#'
#'
#' ####################  ProjectServiceGetProjectByName  ####################
#'
#' library(openapi)
#' var.name <- 'name_example' # character |
#' var.workspace.name <- 'workspace.name_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectByName(name=var.name, workspace.name=var.workspace.name)
#'
#'
#' ####################  ProjectServiceGetProjectCodeVersion  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectCodeVersion(id=var.id)
#'
#'
#' ####################  ProjectServiceGetProjectDatasetCount  ####################
#'
#' library(openapi)
#' var.project.id <- 'project.id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectDatasetCount(project.id=var.project.id)
#'
#'
#' ####################  ProjectServiceGetProjectReadme  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectReadme(id=var.id)
#'
#'
#' ####################  ProjectServiceGetProjectShortName  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectShortName(id=var.id)
#'
#'
#' ####################  ProjectServiceGetProjectTags  ####################
#'
#' library(openapi)
#' var.id <- 'id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjectTags(id=var.id)
#'
#'
#' ####################  ProjectServiceGetProjects  ####################
#'
#' library(openapi)
#' var.page.number <- 56 # integer |
#' var.page.limit <- 56 # integer |
#' var.ascending <- 'ascending_example' # character |
#' var.sort.key <- 'sort.key_example' # character |
#' var.workspace.name <- 'workspace.name_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetProjects(page.number=var.page.number, page.limit=var.page.limit, ascending=var.ascending, sort.key=var.sort.key, workspace.name=var.workspace.name)
#'
#'
#' ####################  ProjectServiceGetSummary  ####################
#'
#' library(openapi)
#' var.entity.id <- 'entity.id_example' # character |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetSummary(entity.id=var.entity.id)
#'
#'
#' ####################  ProjectServiceGetUrlForArtifact  ####################
#'
#' library(openapi)
#' var.body <- ModeldbGetUrlForArtifact$new() # ModeldbGetUrlForArtifact |
#'
#' #artifacts
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceGetUrlForArtifact(var.body)
#'
#'
#' ####################  ProjectServiceLogArtifacts  ####################
#'
#' library(openapi)
#' var.body <- ModeldbLogProjectArtifacts$new() # ModeldbLogProjectArtifacts |
#'
#' #artifacts
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceLogArtifacts(var.body)
#'
#'
#' ####################  ProjectServiceLogProjectCodeVersion  ####################
#'
#' library(openapi)
#' var.body <- ModeldbLogProjectCodeVersion$new() # ModeldbLogProjectCodeVersion |
#'
#' #code version
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceLogProjectCodeVersion(var.body)
#'
#'
#' ####################  ProjectServiceSetProjectReadme  ####################
#'
#' library(openapi)
#' var.body <- ModeldbSetProjectReadme$new() # ModeldbSetProjectReadme |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceSetProjectReadme(var.body)
#'
#'
#' ####################  ProjectServiceSetProjectShortName  ####################
#'
#' library(openapi)
#' var.body <- ModeldbSetProjectShortName$new() # ModeldbSetProjectShortName |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceSetProjectShortName(var.body)
#'
#'
#' ####################  ProjectServiceUpdateProjectAttributes  ####################
#'
#' library(openapi)
#' var.body <- ModeldbUpdateProjectAttributes$new() # ModeldbUpdateProjectAttributes |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceUpdateProjectAttributes(var.body)
#'
#'
#' ####################  ProjectServiceUpdateProjectDescription  ####################
#'
#' library(openapi)
#' var.body <- ModeldbUpdateProjectDescription$new() # ModeldbUpdateProjectDescription |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceUpdateProjectDescription(var.body)
#'
#'
#' ####################  ProjectServiceUpdateProjectName  ####################
#'
#' library(openapi)
#' var.body <- ModeldbUpdateProjectName$new() # ModeldbUpdateProjectName |
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceUpdateProjectName(var.body)
#'
#'
#' ####################  ProjectServiceVerifyConnection  ####################
#'
#' library(openapi)
#'
#' api.instance <- ProjectServiceApi$new()
#'
#' result <- api.instance$ProjectServiceVerifyConnection()
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ProjectServiceApi <- R6::R6Class(
  'ProjectServiceApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    ProjectServiceAddProjectAttributes = function(body, ...){
      apiResponse <- self$ProjectServiceAddProjectAttributesWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceAddProjectAttributesWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/addProjectAttributes"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbAddProjectAttributesResponse", loadNamespace("openapi"))
          resp
          ,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceAddProjectTag = function(body, ...){
      apiResponse <- self$ProjectServiceAddProjectTagWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceAddProjectTagWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/addProjectTag"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbAddProjectTagResponse", loadNamespace("openapi"))
          resp
          ,

          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceAddProjectTags = function(body, ...){
      apiResponse <- self$ProjectServiceAddProjectTagsWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceAddProjectTagsWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/addProjectTags"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbAddProjectTagsResponse", loadNamespace("openapi"))
          resp
          ,

          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceCreateProject = function(body, ...){
      apiResponse <- self$ProjectServiceCreateProjectWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceCreateProjectWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/createProject"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          resp
          ,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeepCopyProject = function(body, ...){
      apiResponse <- self$ProjectServiceDeepCopyProjectWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeepCopyProjectWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deepCopyProject"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          #self$apiClient$deserialize(resp, "ModeldbDeepCopyProjectResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteArtifact = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteArtifactWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteArtifactWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteArtifact"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectArtifactResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteProject = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteProjectWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteProjectWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteProject"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteProjectAttributes = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteProjectAttributesWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteProjectAttributesWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteProjectAttributes"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectAttributesResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteProjectTag = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteProjectTagWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteProjectTagWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteProjectTag"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectTagResponse", loadNamespace("openapi"))
          resp
          ,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteProjectTags = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteProjectTagsWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteProjectTagsWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteProjectTags"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectTagsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceDeleteProjects = function(body, ...){
      apiResponse <- self$ProjectServiceDeleteProjectsWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceDeleteProjectsWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/deleteProjects"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbDeleteProjectsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceFindProjects = function(body, ...){
      apiResponse <- self$ProjectServiceFindProjectsWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceFindProjectsWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/findProjects"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          #self$apiClient$deserialize(resp, "ModeldbFindProjectsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetArtifacts = function(id=NULL, key=NULL, ...){
      apiResponse <- self$ProjectServiceGetArtifactsWithHttpInfo(id, key, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetArtifactsWithHttpInfo = function(id=NULL, key=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      queryParams['key'] <- key

      body <- NULL
      urlPath <- "/project/getArtifacts"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetArtifactsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectAttributes = function(id=NULL, attribute.keys=NULL, get.all=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectAttributesWithHttpInfo(id, attribute.keys, get.all, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectAttributesWithHttpInfo = function(id=NULL, attribute.keys=NULL, get.all=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      queryParams['attribute_keys'] <- attribute.keys

      queryParams['get_all'] <- get.all

      body <- NULL
      urlPath <- "/project/getProjectAttributes"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetAttributesResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectById = function(id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectByIdWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectByIdWithHttpInfo = function(id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      body <- NULL
      urlPath <- "/project/getProjectById"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectByIdResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectByName = function(name=NULL, workspace.name=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectByNameWithHttpInfo(name, workspace.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectByNameWithHttpInfo = function(name=NULL, workspace.name=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['name'] <- name

      queryParams['workspace_name'] <- workspace.name

      body <- NULL
      urlPath <- "/project/getProjectByName"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectByNameResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectCodeVersion = function(id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectCodeVersionWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectCodeVersionWithHttpInfo = function(id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      body <- NULL
      urlPath <- "/project/getProjectCodeVersion"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectCodeVersionResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectDatasetCount = function(project.id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectDatasetCountWithHttpInfo(project.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectDatasetCountWithHttpInfo = function(project.id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['project_id'] <- project.id

      body <- NULL
      urlPath <- "/project/getProjectDatasetCount"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectDatasetCountResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectReadme = function(id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectReadmeWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectReadmeWithHttpInfo = function(id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      body <- NULL
      urlPath <- "/project/getProjectReadme"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectReadmeResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectShortName = function(id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectShortNameWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectShortNameWithHttpInfo = function(id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      body <- NULL
      urlPath <- "/project/getProjectShortName"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectShortNameResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjectTags = function(id=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectTagsWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectTagsWithHttpInfo = function(id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['id'] <- id

      body <- NULL
      urlPath <- "/project/getProjectTags"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetTagsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetProjects = function(page.number=NULL, page.limit=NULL, ascending=NULL, sort.key=NULL, workspace.name=NULL, ...){
      apiResponse <- self$ProjectServiceGetProjectsWithHttpInfo(page.number, page.limit, ascending, sort.key, workspace.name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetProjectsWithHttpInfo = function(page.number=NULL, page.limit=NULL, ascending=NULL, sort.key=NULL, workspace.name=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['page_number'] <- page.number

      queryParams['page_limit'] <- page.limit

      queryParams['ascending'] <- ascending

      queryParams['sort_key'] <- sort.key

      queryParams['workspace_name'] <- workspace.name

      body <- NULL
      urlPath <- "/project/getProjects"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetProjectsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetSummary = function(entity.id=NULL, ...){
      apiResponse <- self$ProjectServiceGetSummaryWithHttpInfo(entity.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetSummaryWithHttpInfo = function(entity.id=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['entityId'] <- entity.id

      body <- NULL
      urlPath <- "/project/getSummary"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetSummaryResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceGetUrlForArtifact = function(body, ...){
      apiResponse <- self$ProjectServiceGetUrlForArtifactWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceGetUrlForArtifactWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/getUrlForArtifact"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbGetUrlForArtifactResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceLogArtifacts = function(body, ...){
      apiResponse <- self$ProjectServiceLogArtifactsWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceLogArtifactsWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/logArtifacts"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbLogProjectArtifactsResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceLogProjectCodeVersion = function(body, ...){
      apiResponse <- self$ProjectServiceLogProjectCodeVersionWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceLogProjectCodeVersionWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/logProjectCodeVersion"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbLogProjectCodeVersionResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceSetProjectReadme = function(body, ...){
      apiResponse <- self$ProjectServiceSetProjectReadmeWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceSetProjectReadmeWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/setProjectReadme"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbSetProjectReadmeResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceSetProjectShortName = function(body, ...){
      apiResponse <- self$ProjectServiceSetProjectShortNameWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceSetProjectShortNameWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/setProjectShortName"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbSetProjectShortNameResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceUpdateProjectAttributes = function(body, ...){
      apiResponse <- self$ProjectServiceUpdateProjectAttributesWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceUpdateProjectAttributesWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/updateProjectAttributes"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbUpdateProjectAttributesResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceUpdateProjectDescription = function(body, ...){
      apiResponse <- self$ProjectServiceUpdateProjectDescriptionWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceUpdateProjectDescriptionWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/updateProjectDescription"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbUpdateProjectDescriptionResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceUpdateProjectName = function(body, ...){
      apiResponse <- self$ProjectServiceUpdateProjectNameWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceUpdateProjectNameWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/project/updateProjectName"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbUpdateProjectNameResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ProjectServiceVerifyConnection = function(...){
      apiResponse <- self$ProjectServiceVerifyConnectionWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ProjectServiceVerifyConnectionWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/project/verifyConnection"

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          # self$apiClient$deserialize(resp, "ModeldbVerifyConnectionResponse", loadNamespace("openapi"))
          resp,
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
