# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RuntimeError
#'
#' @description RuntimeError Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field error  character [optional]
#'
#' @field code  integer [optional]
#'
#' @field message  character [optional]
#'
#' @field details  list( \link{ProtobufAny} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RuntimeError <- R6::R6Class(
  'RuntimeError',
  public = list(
    `error` = NULL,
    `code` = NULL,
    `message` = NULL,
    `details` = NULL,
    initialize = function(
        `error`=NULL, `code`=NULL, `message`=NULL, `details`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
      if (!is.null(`code`)) {
        stopifnot(is.numeric(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`details`)) {
        stopifnot(is.vector(`details`), length(`details`) != 0)
        sapply(`details`, function(x) stopifnot(R6::is.R6(x)))
        self$`details` <- `details`
      }
    },
    toJSON = function() {
      RuntimeErrorObject <- list()
      if (!is.null(self$`error`)) {
        RuntimeErrorObject[['error']] <-
          self$`error`
      }
      if (!is.null(self$`code`)) {
        RuntimeErrorObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`message`)) {
        RuntimeErrorObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`details`)) {
        RuntimeErrorObject[['details']] <-
          lapply(self$`details`, function(x) x$toJSON())
      }

      RuntimeErrorObject
    },
    fromJSON = function(RuntimeErrorJson) {
      RuntimeErrorObject <- jsonlite::fromJSON(RuntimeErrorJson)
      if (!is.null(RuntimeErrorObject$`error`)) {
        self$`error` <- RuntimeErrorObject$`error`
      }
      if (!is.null(RuntimeErrorObject$`code`)) {
        self$`code` <- RuntimeErrorObject$`code`
      }
      if (!is.null(RuntimeErrorObject$`message`)) {
        self$`message` <- RuntimeErrorObject$`message`
      }
      if (!is.null(RuntimeErrorObject$`details`)) {
        self$`details` <- ApiClient$new()$deserializeObj(RuntimeErrorObject$`details`, "array[ProtobufAny]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`error`)) {
        sprintf(
        '"error":
          "%s"
                ',
        self$`error`
        )},
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          %d
                ',
        self$`code`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`details`)) {
        sprintf(
        '"details":
        [%s]
',
        paste(sapply(self$`details`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RuntimeErrorJson) {
      RuntimeErrorObject <- jsonlite::fromJSON(RuntimeErrorJson)
      self$`error` <- RuntimeErrorObject$`error`
      self$`code` <- RuntimeErrorObject$`code`
      self$`message` <- RuntimeErrorObject$`message`
      self$`details` <- ApiClient$new()$deserializeObj(RuntimeErrorObject$`details`, "array[ProtobufAny]", loadNamespace("openapi"))
      self
    }
  )
)

