# modeldb/ProjectService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UacCollaboratorPermissions
#'
#' @description UacCollaboratorPermissions Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field collaborator_type  \link{CollaboratorTypeEnumCollaboratorType} [optional]
#'
#' @field can_deploy  \link{TernaryEnumTernary} [optional]
#'
#' @field can_predict  \link{TernaryEnumTernary} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UacCollaboratorPermissions <- R6::R6Class(
  'UacCollaboratorPermissions',
  public = list(
    `collaborator_type` = NULL,
    `can_deploy` = NULL,
    `can_predict` = NULL,
    initialize = function(
        `collaborator_type`=NULL, `can_deploy`=NULL, `can_predict`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`collaborator_type`)) {
        stopifnot(R6::is.R6(`collaborator_type`))
        self$`collaborator_type` <- `collaborator_type`
      }
      if (!is.null(`can_deploy`)) {
        stopifnot(R6::is.R6(`can_deploy`))
        self$`can_deploy` <- `can_deploy`
      }
      if (!is.null(`can_predict`)) {
        stopifnot(R6::is.R6(`can_predict`))
        self$`can_predict` <- `can_predict`
      }
    },
    toJSON = function() {
      UacCollaboratorPermissionsObject <- list()
      if (!is.null(self$`collaborator_type`)) {
        UacCollaboratorPermissionsObject[['collaborator_type']] <-
          self$`collaborator_type`$toJSON()
      }
      if (!is.null(self$`can_deploy`)) {
        UacCollaboratorPermissionsObject[['can_deploy']] <-
          self$`can_deploy`$toJSON()
      }
      if (!is.null(self$`can_predict`)) {
        UacCollaboratorPermissionsObject[['can_predict']] <-
          self$`can_predict`$toJSON()
      }

      UacCollaboratorPermissionsObject
    },
    fromJSON = function(UacCollaboratorPermissionsJson) {
      UacCollaboratorPermissionsObject <- jsonlite::fromJSON(UacCollaboratorPermissionsJson)
      if (!is.null(UacCollaboratorPermissionsObject$`collaborator_type`)) {
        collaborator_typeObject <- CollaboratorTypeEnumCollaboratorType$new()
        collaborator_typeObject$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$collaborator_type, auto_unbox = TRUE, digits = NA))
        self$`collaborator_type` <- collaborator_typeObject
      }
      if (!is.null(UacCollaboratorPermissionsObject$`can_deploy`)) {
        can_deployObject <- TernaryEnumTernary$new()
        can_deployObject$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$can_deploy, auto_unbox = TRUE, digits = NA))
        self$`can_deploy` <- can_deployObject
      }
      if (!is.null(UacCollaboratorPermissionsObject$`can_predict`)) {
        can_predictObject <- TernaryEnumTernary$new()
        can_predictObject$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$can_predict, auto_unbox = TRUE, digits = NA))
        self$`can_predict` <- can_predictObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`collaborator_type`)) {
        sprintf(
        '"collaborator_type":
        %s
        ',
        jsonlite::toJSON(self$`collaborator_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`can_deploy`)) {
        sprintf(
        '"can_deploy":
        %s
        ',
        jsonlite::toJSON(self$`can_deploy`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`can_predict`)) {
        sprintf(
        '"can_predict":
        %s
        ',
        jsonlite::toJSON(self$`can_predict`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UacCollaboratorPermissionsJson) {
      UacCollaboratorPermissionsObject <- jsonlite::fromJSON(UacCollaboratorPermissionsJson)
      self$`collaborator_type` <- CollaboratorTypeEnumCollaboratorType$new()$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$collaborator_type, auto_unbox = TRUE, digits = NA))
      self$`can_deploy` <- TernaryEnumTernary$new()$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$can_deploy, auto_unbox = TRUE, digits = NA))
      self$`can_predict` <- TernaryEnumTernary$new()$fromJSON(jsonlite::toJSON(UacCollaboratorPermissionsObject$can_predict, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

