# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetUrlForArtifact")

model.instance <- ModeldbGetUrlForArtifact$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("artifact_type", {
  # tests for the property `artifact_type` (ArtifactTypeEnumArtifactType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifact_type`, "EXPECTED_RESULT")
})

test_that("part_number", {
  # tests for the property `part_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`part_number`, "EXPECTED_RESULT")
})

