# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGitSnapshot")

model.instance <- ModeldbGitSnapshot$new()

test_that("filepaths", {
  # tests for the property `filepaths` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`filepaths`, "EXPECTED_RESULT")
})

test_that("repo", {
  # tests for the property `repo` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`repo`, "EXPECTED_RESULT")
})

test_that("hash", {
  # tests for the property `hash` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hash`, "EXPECTED_RESULT")
})

test_that("is_dirty", {
  # tests for the property `is_dirty` (TernaryEnumTernary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_dirty`, "EXPECTED_RESULT")
})

