# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetProjectShortNameResponse")

model.instance <- ModeldbGetProjectShortNameResponse$new()

test_that("short_name", {
  # tests for the property `short_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`short_name`, "EXPECTED_RESULT")
})

