# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbCodeVersion")

model.instance <- ModeldbCodeVersion$new()

test_that("git_snapshot", {
  # tests for the property `git_snapshot` (ModeldbGitSnapshot)

  # uncomment below to test the property 
  #expect_equal(model.instance$`git_snapshot`, "EXPECTED_RESULT")
})

test_that("code_archive", {
  # tests for the property `code_archive` (CommonArtifact)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code_archive`, "EXPECTED_RESULT")
})

test_that("date_logged", {
  # tests for the property `date_logged` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date_logged`, "EXPECTED_RESULT")
})

