# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommonKeyValueQuery")

model.instance <- CommonKeyValueQuery$new()

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("value_type", {
  # tests for the property `value_type` (ValueTypeEnumValueType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value_type`, "EXPECTED_RESULT")
})

test_that("operator", {
  # tests for the property `operator` (OperatorEnumOperator)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operator`, "EXPECTED_RESULT")
})

