# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbFindProjects")

model.instance <- ModeldbFindProjects$new()

test_that("project_ids", {
  # tests for the property `project_ids` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`project_ids`, "EXPECTED_RESULT")
})

test_that("predicates", {
  # tests for the property `predicates` (array[CommonKeyValueQuery])

  # uncomment below to test the property 
  #expect_equal(model.instance$`predicates`, "EXPECTED_RESULT")
})

test_that("ids_only", {
  # tests for the property `ids_only` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ids_only`, "EXPECTED_RESULT")
})

test_that("workspace_name", {
  # tests for the property `workspace_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_name`, "EXPECTED_RESULT")
})

test_that("page_number", {
  # tests for the property `page_number` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`page_number`, "EXPECTED_RESULT")
})

test_that("page_limit", {
  # tests for the property `page_limit` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`page_limit`, "EXPECTED_RESULT")
})

test_that("ascending", {
  # tests for the property `ascending` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ascending`, "EXPECTED_RESULT")
})

test_that("sort_key", {
  # tests for the property `sort_key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sort_key`, "EXPECTED_RESULT")
})

