# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbLogProjectCodeVersion")

model.instance <- ModeldbLogProjectCodeVersion$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("code_version", {
  # tests for the property `code_version` (ModeldbCodeVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code_version`, "EXPECTED_RESULT")
})

