# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetUrlForArtifactResponse")

model.instance <- ModeldbGetUrlForArtifactResponse$new()

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("fields", {
  # tests for the property `fields` (map(character))

  # uncomment below to test the property 
  #expect_equal(model.instance$`fields`, "EXPECTED_RESULT")
})

test_that("multipart_upload_ok", {
  # tests for the property `multipart_upload_ok` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`multipart_upload_ok`, "EXPECTED_RESULT")
})

