# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommonArtifact")

model.instance <- CommonArtifact$new()

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("path_only", {
  # tests for the property `path_only` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`path_only`, "EXPECTED_RESULT")
})

test_that("artifact_type", {
  # tests for the property `artifact_type` (ArtifactTypeEnumArtifactType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifact_type`, "EXPECTED_RESULT")
})

test_that("linked_artifact_id", {
  # tests for the property `linked_artifact_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`linked_artifact_id`, "EXPECTED_RESULT")
})

test_that("filename_extension", {
  # tests for the property `filename_extension` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`filename_extension`, "EXPECTED_RESULT")
})

