# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetProjectsResponse")

model.instance <- ModeldbGetProjectsResponse$new()

test_that("projects", {
  # tests for the property `projects` (array[ModeldbProject])

  # uncomment below to test the property 
  #expect_equal(model.instance$`projects`, "EXPECTED_RESULT")
})

test_that("total_records", {
  # tests for the property `total_records` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_records`, "EXPECTED_RESULT")
})

