# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbAddProjectTag")

model.instance <- ModeldbAddProjectTag$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})

