# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetAttributesResponse")

model.instance <- ModeldbGetAttributesResponse$new()

test_that("attributes", {
  # tests for the property `attributes` (array[CommonKeyValue])

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

