# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProjectServiceApi")

api.instance <- ProjectServiceApi$new()

test_that("ProjectServiceAddProjectAttributes", {
  # tests for ProjectServiceAddProjectAttributes
  # base path: http://localhost/v1
  # @param body ModeldbAddProjectAttributes 
  # @return [ModeldbAddProjectAttributesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceAddProjectTag", {
  # tests for ProjectServiceAddProjectTag
  # base path: http://localhost/v1
  # @param body ModeldbAddProjectTag 
  # @return [ModeldbAddProjectTagResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceAddProjectTags", {
  # tests for ProjectServiceAddProjectTags
  # base path: http://localhost/v1
  # @param body ModeldbAddProjectTags 
  # @return [ModeldbAddProjectTagsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceCreateProject", {
  # tests for ProjectServiceCreateProject
  # base path: http://localhost/v1
  # @param body ModeldbCreateProject 
  # @return [ModeldbCreateProjectResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeepCopyProject", {
  # tests for ProjectServiceDeepCopyProject
  # base path: http://localhost/v1
  # @param body ModeldbDeepCopyProject 
  # @return [ModeldbDeepCopyProjectResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteArtifact", {
  # tests for ProjectServiceDeleteArtifact
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProjectArtifact 
  # @return [ModeldbDeleteProjectArtifactResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteProject", {
  # tests for ProjectServiceDeleteProject
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProject 
  # @return [ModeldbDeleteProjectResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteProjectAttributes", {
  # tests for ProjectServiceDeleteProjectAttributes
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProjectAttributes 
  # @return [ModeldbDeleteProjectAttributesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteProjectTag", {
  # tests for ProjectServiceDeleteProjectTag
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProjectTag 
  # @return [ModeldbDeleteProjectTagResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteProjectTags", {
  # tests for ProjectServiceDeleteProjectTags
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProjectTags 
  # @return [ModeldbDeleteProjectTagsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceDeleteProjects", {
  # tests for ProjectServiceDeleteProjects
  # base path: http://localhost/v1
  # @param body ModeldbDeleteProjects 
  # @return [ModeldbDeleteProjectsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceFindProjects", {
  # tests for ProjectServiceFindProjects
  # base path: http://localhost/v1
  # queries
  # @param body ModeldbFindProjects 
  # @return [ModeldbFindProjectsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetArtifacts", {
  # tests for ProjectServiceGetArtifacts
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @param key character  (optional)
  # @return [ModeldbGetArtifactsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectAttributes", {
  # tests for ProjectServiceGetProjectAttributes
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @param attribute.keys array[character]  (optional)
  # @param get.all character  (optional)
  # @return [ModeldbGetAttributesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectById", {
  # tests for ProjectServiceGetProjectById
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @return [ModeldbGetProjectByIdResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectByName", {
  # tests for ProjectServiceGetProjectByName
  # base path: http://localhost/v1
  # @param name character  (optional)
  # @param workspace.name character  (optional)
  # @return [ModeldbGetProjectByNameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectCodeVersion", {
  # tests for ProjectServiceGetProjectCodeVersion
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @return [ModeldbGetProjectCodeVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectDatasetCount", {
  # tests for ProjectServiceGetProjectDatasetCount
  # base path: http://localhost/v1
  # @param project.id character  (optional)
  # @return [ModeldbGetProjectDatasetCountResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectReadme", {
  # tests for ProjectServiceGetProjectReadme
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @return [ModeldbGetProjectReadmeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectShortName", {
  # tests for ProjectServiceGetProjectShortName
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @return [ModeldbGetProjectShortNameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjectTags", {
  # tests for ProjectServiceGetProjectTags
  # base path: http://localhost/v1
  # @param id character  (optional)
  # @return [ModeldbGetTagsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetProjects", {
  # tests for ProjectServiceGetProjects
  # base path: http://localhost/v1
  # @param page.number integer  (optional)
  # @param page.limit integer  (optional)
  # @param ascending character  (optional)
  # @param sort.key character  (optional)
  # @param workspace.name character  (optional)
  # @return [ModeldbGetProjectsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetSummary", {
  # tests for ProjectServiceGetSummary
  # base path: http://localhost/v1
  # @param entity.id character  (optional)
  # @return [ModeldbGetSummaryResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceGetUrlForArtifact", {
  # tests for ProjectServiceGetUrlForArtifact
  # base path: http://localhost/v1
  # artifacts
  # @param body ModeldbGetUrlForArtifact 
  # @return [ModeldbGetUrlForArtifactResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceLogArtifacts", {
  # tests for ProjectServiceLogArtifacts
  # base path: http://localhost/v1
  # artifacts
  # @param body ModeldbLogProjectArtifacts 
  # @return [ModeldbLogProjectArtifactsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceLogProjectCodeVersion", {
  # tests for ProjectServiceLogProjectCodeVersion
  # base path: http://localhost/v1
  # code version
  # @param body ModeldbLogProjectCodeVersion 
  # @return [ModeldbLogProjectCodeVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceSetProjectReadme", {
  # tests for ProjectServiceSetProjectReadme
  # base path: http://localhost/v1
  # @param body ModeldbSetProjectReadme 
  # @return [ModeldbSetProjectReadmeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceSetProjectShortName", {
  # tests for ProjectServiceSetProjectShortName
  # base path: http://localhost/v1
  # @param body ModeldbSetProjectShortName 
  # @return [ModeldbSetProjectShortNameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceUpdateProjectAttributes", {
  # tests for ProjectServiceUpdateProjectAttributes
  # base path: http://localhost/v1
  # @param body ModeldbUpdateProjectAttributes 
  # @return [ModeldbUpdateProjectAttributesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceUpdateProjectDescription", {
  # tests for ProjectServiceUpdateProjectDescription
  # base path: http://localhost/v1
  # @param body ModeldbUpdateProjectDescription 
  # @return [ModeldbUpdateProjectDescriptionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceUpdateProjectName", {
  # tests for ProjectServiceUpdateProjectName
  # base path: http://localhost/v1
  # @param body ModeldbUpdateProjectName 
  # @return [ModeldbUpdateProjectNameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ProjectServiceVerifyConnection", {
  # tests for ProjectServiceVerifyConnection
  # base path: http://localhost/v1
  # @return [ModeldbVerifyConnectionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

