# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbMetricsSummary")

model.instance <- ModeldbMetricsSummary$new()

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("min_value", {
  # tests for the property `min_value` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`min_value`, "EXPECTED_RESULT")
})

test_that("max_value", {
  # tests for the property `max_value` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`max_value`, "EXPECTED_RESULT")
})

