# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbSetProjectShortNameResponse")

model.instance <- ModeldbSetProjectShortNameResponse$new()

test_that("project", {
  # tests for the property `project` (ModeldbProject)

  # uncomment below to test the property 
  #expect_equal(model.instance$`project`, "EXPECTED_RESULT")
})

