# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbLogProjectArtifacts")

model.instance <- ModeldbLogProjectArtifacts$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("artifacts", {
  # tests for the property `artifacts` (array[CommonArtifact])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifacts`, "EXPECTED_RESULT")
})

