# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbUpdateProjectAttributes")

model.instance <- ModeldbUpdateProjectAttributes$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("attribute", {
  # tests for the property `attribute` (CommonKeyValue)

  # uncomment below to test the property 
  #expect_equal(model.instance$`attribute`, "EXPECTED_RESULT")
})

