# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbSetProjectReadme")

model.instance <- ModeldbSetProjectReadme$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("readme_text", {
  # tests for the property `readme_text` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme_text`, "EXPECTED_RESULT")
})

