# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbSetProjectShortName")

model.instance <- ModeldbSetProjectShortName$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("short_name", {
  # tests for the property `short_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`short_name`, "EXPECTED_RESULT")
})

