# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbDeleteProjects")

model.instance <- ModeldbDeleteProjects$new()

test_that("ids", {
  # tests for the property `ids` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`ids`, "EXPECTED_RESULT")
})

