# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetArtifactsResponse")

model.instance <- ModeldbGetArtifactsResponse$new()

test_that("artifacts", {
  # tests for the property `artifacts` (array[CommonArtifact])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifacts`, "EXPECTED_RESULT")
})

