# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbDeleteProjectAttributes")

model.instance <- ModeldbDeleteProjectAttributes$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("attribute_keys", {
  # tests for the property `attribute_keys` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`attribute_keys`, "EXPECTED_RESULT")
})

test_that("delete_all", {
  # tests for the property `delete_all` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`delete_all`, "EXPECTED_RESULT")
})

