# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UacCollaboratorPermissions")

model.instance <- UacCollaboratorPermissions$new()

test_that("collaborator_type", {
  # tests for the property `collaborator_type` (CollaboratorTypeEnumCollaboratorType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`collaborator_type`, "EXPECTED_RESULT")
})

test_that("can_deploy", {
  # tests for the property `can_deploy` (TernaryEnumTernary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`can_deploy`, "EXPECTED_RESULT")
})

test_that("can_predict", {
  # tests for the property `can_predict` (TernaryEnumTernary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`can_predict`, "EXPECTED_RESULT")
})

