# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbVerifyConnectionResponse")

model.instance <- ModeldbVerifyConnectionResponse$new()

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

