# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetProjectByNameResponse")

model.instance <- ModeldbGetProjectByNameResponse$new()

test_that("project_by_user", {
  # tests for the property `project_by_user` (ModeldbProject)

  # uncomment below to test the property 
  #expect_equal(model.instance$`project_by_user`, "EXPECTED_RESULT")
})

test_that("shared_projects", {
  # tests for the property `shared_projects` (array[ModeldbProject])

  # uncomment below to test the property 
  #expect_equal(model.instance$`shared_projects`, "EXPECTED_RESULT")
})

