# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbCreateProject")

model.instance <- ModeldbCreateProject$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (array[CommonKeyValue])

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("readme_text", {
  # tests for the property `readme_text` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme_text`, "EXPECTED_RESULT")
})

test_that("project_visibility", {
  # tests for the property `project_visibility` (ModeldbProjectVisibility)

  # uncomment below to test the property 
  #expect_equal(model.instance$`project_visibility`, "EXPECTED_RESULT")
})

test_that("artifacts", {
  # tests for the property `artifacts` (array[CommonArtifact])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifacts`, "EXPECTED_RESULT")
})

test_that("workspace_name", {
  # tests for the property `workspace_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_name`, "EXPECTED_RESULT")
})

test_that("date_created", {
  # tests for the property `date_created` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date_created`, "EXPECTED_RESULT")
})

test_that("custom_permission", {
  # tests for the property `custom_permission` (UacCollaboratorPermissions)

  # uncomment below to test the property 
  #expect_equal(model.instance$`custom_permission`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (UacResourceVisibility)

  # uncomment below to test the property 
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

