# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbDeleteProjectArtifact")

model.instance <- ModeldbDeleteProjectArtifact$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

