# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetTagsResponse")

model.instance <- ModeldbGetTagsResponse$new()

test_that("tags", {
  # tests for the property `tags` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

