# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModeldbGetProjectCodeVersionResponse")

model.instance <- ModeldbGetProjectCodeVersionResponse$new()

test_that("code_version", {
  # tests for the property `code_version` (ModeldbCodeVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code_version`, "EXPECTED_RESULT")
})

