# Title     : Testing the generated files
# Objective : Example usage of the code, generated by R
# Created by: sidi
# Created on: 05.06.21
library(stringr)
library(magrittr)
source(file ="project.r")

Sys.setenv(VERTA_EMAIL = "qwerty@moo.com",
           VERTA_DEV_KEY = "1234-1234-1234-1234")

# ProjectService_addProjectAttributes(list())

# POST Create Project with Random ID ----------
create_proj_response <-  ProjectService_createProject(
  list(
    name = str_glue("Stefan-test{runif(1)}"),
    tags=list("demo1","demo2"),
    attributes = list(list(key="team",value="verta"))
  )
)
# create_proj_response <- .Last.value
#read out the project response -------
create_proj_response %>% content() %>% print


id <- (create_proj_response %>% content())[["project"]][["id"]]


# GET project tags-----------
proj_tags_call <- ProjectService_getProjectTags(id=id) %>% content()
print(str_glue("project tags:{proj_tags_call$tags}"))

# GET project attributes-----------
proj_tags_attributes <- ProjectService_getProjectAttributes(id=id,
                                                            attribute_keys = NULL,
                                                            get_all = T
) %>% content()
# proj_tags_attributes %>% content()

print(str_glue("project attributes:{proj_tags_attributes$attributes}"))


